// Code generated by mockery. DO NOT EDIT.

package samlsp

import (
	samlsp "github.com/adalundhe/saml-gin/samlsp"
	mock "github.com/stretchr/testify/mock"
)

// MockSessionWithAttributes is an autogenerated mock type for the SessionWithAttributes type
type MockSessionWithAttributes struct {
	mock.Mock
}

type MockSessionWithAttributes_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionWithAttributes) EXPECT() *MockSessionWithAttributes_Expecter {
	return &MockSessionWithAttributes_Expecter{mock: &_m.Mock}
}

// GetAttributes provides a mock function with no fields
func (_m *MockSessionWithAttributes) GetAttributes() samlsp.Attributes {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAttributes")
	}

	var r0 samlsp.Attributes
	if rf, ok := ret.Get(0).(func() samlsp.Attributes); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(samlsp.Attributes)
		}
	}

	return r0
}

// MockSessionWithAttributes_GetAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttributes'
type MockSessionWithAttributes_GetAttributes_Call struct {
	*mock.Call
}

// GetAttributes is a helper method to define mock.On call
func (_e *MockSessionWithAttributes_Expecter) GetAttributes() *MockSessionWithAttributes_GetAttributes_Call {
	return &MockSessionWithAttributes_GetAttributes_Call{Call: _e.mock.On("GetAttributes")}
}

func (_c *MockSessionWithAttributes_GetAttributes_Call) Run(run func()) *MockSessionWithAttributes_GetAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionWithAttributes_GetAttributes_Call) Return(_a0 samlsp.Attributes) *MockSessionWithAttributes_GetAttributes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionWithAttributes_GetAttributes_Call) RunAndReturn(run func() samlsp.Attributes) *MockSessionWithAttributes_GetAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionWithAttributes creates a new instance of MockSessionWithAttributes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionWithAttributes(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionWithAttributes {
	mock := &MockSessionWithAttributes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
