// Code generated by mockery. DO NOT EDIT.

package samlsp

import (
	saml "github.com/adalundhe/saml-gin"
	mock "github.com/stretchr/testify/mock"
)

// MockAssertionHandler is an autogenerated mock type for the AssertionHandler type
type MockAssertionHandler struct {
	mock.Mock
}

type MockAssertionHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAssertionHandler) EXPECT() *MockAssertionHandler_Expecter {
	return &MockAssertionHandler_Expecter{mock: &_m.Mock}
}

// HandleAssertion provides a mock function with given fields: assertion
func (_m *MockAssertionHandler) HandleAssertion(assertion *saml.Assertion) error {
	ret := _m.Called(assertion)

	if len(ret) == 0 {
		panic("no return value specified for HandleAssertion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*saml.Assertion) error); ok {
		r0 = rf(assertion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAssertionHandler_HandleAssertion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleAssertion'
type MockAssertionHandler_HandleAssertion_Call struct {
	*mock.Call
}

// HandleAssertion is a helper method to define mock.On call
//   - assertion *saml.Assertion
func (_e *MockAssertionHandler_Expecter) HandleAssertion(assertion interface{}) *MockAssertionHandler_HandleAssertion_Call {
	return &MockAssertionHandler_HandleAssertion_Call{Call: _e.mock.On("HandleAssertion", assertion)}
}

func (_c *MockAssertionHandler_HandleAssertion_Call) Run(run func(assertion *saml.Assertion)) *MockAssertionHandler_HandleAssertion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*saml.Assertion))
	})
	return _c
}

func (_c *MockAssertionHandler_HandleAssertion_Call) Return(_a0 error) *MockAssertionHandler_HandleAssertion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAssertionHandler_HandleAssertion_Call) RunAndReturn(run func(*saml.Assertion) error) *MockAssertionHandler_HandleAssertion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAssertionHandler creates a new instance of MockAssertionHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssertionHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssertionHandler {
	mock := &MockAssertionHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
