// Code generated by mockery. DO NOT EDIT.

package samlsp

import (
	http "net/http"

	samlsp "github.com/adalundhe/saml-gin/samlsp"
	mock "github.com/stretchr/testify/mock"
)

// MockRequestTracker is an autogenerated mock type for the RequestTracker type
type MockRequestTracker struct {
	mock.Mock
}

type MockRequestTracker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestTracker) EXPECT() *MockRequestTracker_Expecter {
	return &MockRequestTracker_Expecter{mock: &_m.Mock}
}

// GetTrackedRequest provides a mock function with given fields: r, index
func (_m *MockRequestTracker) GetTrackedRequest(r *http.Request, index string) (*samlsp.TrackedRequest, error) {
	ret := _m.Called(r, index)

	if len(ret) == 0 {
		panic("no return value specified for GetTrackedRequest")
	}

	var r0 *samlsp.TrackedRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request, string) (*samlsp.TrackedRequest, error)); ok {
		return rf(r, index)
	}
	if rf, ok := ret.Get(0).(func(*http.Request, string) *samlsp.TrackedRequest); ok {
		r0 = rf(r, index)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*samlsp.TrackedRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request, string) error); ok {
		r1 = rf(r, index)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestTracker_GetTrackedRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrackedRequest'
type MockRequestTracker_GetTrackedRequest_Call struct {
	*mock.Call
}

// GetTrackedRequest is a helper method to define mock.On call
//   - r *http.Request
//   - index string
func (_e *MockRequestTracker_Expecter) GetTrackedRequest(r interface{}, index interface{}) *MockRequestTracker_GetTrackedRequest_Call {
	return &MockRequestTracker_GetTrackedRequest_Call{Call: _e.mock.On("GetTrackedRequest", r, index)}
}

func (_c *MockRequestTracker_GetTrackedRequest_Call) Run(run func(r *http.Request, index string)) *MockRequestTracker_GetTrackedRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request), args[1].(string))
	})
	return _c
}

func (_c *MockRequestTracker_GetTrackedRequest_Call) Return(_a0 *samlsp.TrackedRequest, _a1 error) *MockRequestTracker_GetTrackedRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestTracker_GetTrackedRequest_Call) RunAndReturn(run func(*http.Request, string) (*samlsp.TrackedRequest, error)) *MockRequestTracker_GetTrackedRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrackedRequests provides a mock function with given fields: r
func (_m *MockRequestTracker) GetTrackedRequests(r *http.Request) []samlsp.TrackedRequest {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetTrackedRequests")
	}

	var r0 []samlsp.TrackedRequest
	if rf, ok := ret.Get(0).(func(*http.Request) []samlsp.TrackedRequest); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]samlsp.TrackedRequest)
		}
	}

	return r0
}

// MockRequestTracker_GetTrackedRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrackedRequests'
type MockRequestTracker_GetTrackedRequests_Call struct {
	*mock.Call
}

// GetTrackedRequests is a helper method to define mock.On call
//   - r *http.Request
func (_e *MockRequestTracker_Expecter) GetTrackedRequests(r interface{}) *MockRequestTracker_GetTrackedRequests_Call {
	return &MockRequestTracker_GetTrackedRequests_Call{Call: _e.mock.On("GetTrackedRequests", r)}
}

func (_c *MockRequestTracker_GetTrackedRequests_Call) Run(run func(r *http.Request)) *MockRequestTracker_GetTrackedRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *MockRequestTracker_GetTrackedRequests_Call) Return(_a0 []samlsp.TrackedRequest) *MockRequestTracker_GetTrackedRequests_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRequestTracker_GetTrackedRequests_Call) RunAndReturn(run func(*http.Request) []samlsp.TrackedRequest) *MockRequestTracker_GetTrackedRequests_Call {
	_c.Call.Return(run)
	return _c
}

// StopTrackingRequest provides a mock function with given fields: w, r, index
func (_m *MockRequestTracker) StopTrackingRequest(w http.ResponseWriter, r *http.Request, index string) error {
	ret := _m.Called(w, r, index)

	if len(ret) == 0 {
		panic("no return value specified for StopTrackingRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, string) error); ok {
		r0 = rf(w, r, index)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRequestTracker_StopTrackingRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopTrackingRequest'
type MockRequestTracker_StopTrackingRequest_Call struct {
	*mock.Call
}

// StopTrackingRequest is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - index string
func (_e *MockRequestTracker_Expecter) StopTrackingRequest(w interface{}, r interface{}, index interface{}) *MockRequestTracker_StopTrackingRequest_Call {
	return &MockRequestTracker_StopTrackingRequest_Call{Call: _e.mock.On("StopTrackingRequest", w, r, index)}
}

func (_c *MockRequestTracker_StopTrackingRequest_Call) Run(run func(w http.ResponseWriter, r *http.Request, index string)) *MockRequestTracker_StopTrackingRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request), args[2].(string))
	})
	return _c
}

func (_c *MockRequestTracker_StopTrackingRequest_Call) Return(_a0 error) *MockRequestTracker_StopTrackingRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRequestTracker_StopTrackingRequest_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request, string) error) *MockRequestTracker_StopTrackingRequest_Call {
	_c.Call.Return(run)
	return _c
}

// TrackRequest provides a mock function with given fields: w, r, samlRequestID
func (_m *MockRequestTracker) TrackRequest(w http.ResponseWriter, r *http.Request, samlRequestID string) (string, error) {
	ret := _m.Called(w, r, samlRequestID)

	if len(ret) == 0 {
		panic("no return value specified for TrackRequest")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, string) (string, error)); ok {
		return rf(w, r, samlRequestID)
	}
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, string) string); ok {
		r0 = rf(w, r, samlRequestID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(http.ResponseWriter, *http.Request, string) error); ok {
		r1 = rf(w, r, samlRequestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestTracker_TrackRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrackRequest'
type MockRequestTracker_TrackRequest_Call struct {
	*mock.Call
}

// TrackRequest is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - samlRequestID string
func (_e *MockRequestTracker_Expecter) TrackRequest(w interface{}, r interface{}, samlRequestID interface{}) *MockRequestTracker_TrackRequest_Call {
	return &MockRequestTracker_TrackRequest_Call{Call: _e.mock.On("TrackRequest", w, r, samlRequestID)}
}

func (_c *MockRequestTracker_TrackRequest_Call) Run(run func(w http.ResponseWriter, r *http.Request, samlRequestID string)) *MockRequestTracker_TrackRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request), args[2].(string))
	})
	return _c
}

func (_c *MockRequestTracker_TrackRequest_Call) Return(index string, err error) *MockRequestTracker_TrackRequest_Call {
	_c.Call.Return(index, err)
	return _c
}

func (_c *MockRequestTracker_TrackRequest_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request, string) (string, error)) *MockRequestTracker_TrackRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRequestTracker creates a new instance of MockRequestTracker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestTracker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestTracker {
	mock := &MockRequestTracker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
