// Code generated by mockery. DO NOT EDIT.

package samlsp

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	saml "github.com/adalundhe/saml-gin"

	samlsp "github.com/adalundhe/saml-gin/samlsp"
)

// MockSessionProvider is an autogenerated mock type for the SessionProvider type
type MockSessionProvider struct {
	mock.Mock
}

type MockSessionProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionProvider) EXPECT() *MockSessionProvider_Expecter {
	return &MockSessionProvider_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function with given fields: ctx, assertion
func (_m *MockSessionProvider) CreateSession(ctx *gin.Context, assertion *saml.Assertion) error {
	ret := _m.Called(ctx, assertion)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *saml.Assertion) error); ok {
		r0 = rf(ctx, assertion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionProvider_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionProvider_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx *gin.Context
//   - assertion *saml.Assertion
func (_e *MockSessionProvider_Expecter) CreateSession(ctx interface{}, assertion interface{}) *MockSessionProvider_CreateSession_Call {
	return &MockSessionProvider_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, assertion)}
}

func (_c *MockSessionProvider_CreateSession_Call) Run(run func(ctx *gin.Context, assertion *saml.Assertion)) *MockSessionProvider_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(*saml.Assertion))
	})
	return _c
}

func (_c *MockSessionProvider_CreateSession_Call) Return(_a0 error) *MockSessionProvider_CreateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionProvider_CreateSession_Call) RunAndReturn(run func(*gin.Context, *saml.Assertion) error) *MockSessionProvider_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function with given fields: ctx
func (_m *MockSessionProvider) DeleteSession(ctx *gin.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionProvider_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockSessionProvider_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockSessionProvider_Expecter) DeleteSession(ctx interface{}) *MockSessionProvider_DeleteSession_Call {
	return &MockSessionProvider_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx)}
}

func (_c *MockSessionProvider_DeleteSession_Call) Run(run func(ctx *gin.Context)) *MockSessionProvider_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockSessionProvider_DeleteSession_Call) Return(_a0 error) *MockSessionProvider_DeleteSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionProvider_DeleteSession_Call) RunAndReturn(run func(*gin.Context) error) *MockSessionProvider_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: ctx
func (_m *MockSessionProvider) GetSession(ctx *gin.Context) (samlsp.Session, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 samlsp.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (samlsp.Session, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) samlsp.Session); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(samlsp.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionProvider_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockSessionProvider_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockSessionProvider_Expecter) GetSession(ctx interface{}) *MockSessionProvider_GetSession_Call {
	return &MockSessionProvider_GetSession_Call{Call: _e.mock.On("GetSession", ctx)}
}

func (_c *MockSessionProvider_GetSession_Call) Run(run func(ctx *gin.Context)) *MockSessionProvider_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockSessionProvider_GetSession_Call) Return(_a0 samlsp.Session, _a1 error) *MockSessionProvider_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionProvider_GetSession_Call) RunAndReturn(run func(*gin.Context) (samlsp.Session, error)) *MockSessionProvider_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionProvider creates a new instance of MockSessionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionProvider {
	mock := &MockSessionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
