// Code generated by mockery. DO NOT EDIT.

package samlsp

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	saml "github.com/adalundhe/saml-gin"

	samlsp "github.com/adalundhe/saml-gin/samlsp"

	time "time"
)

// MockSessionProvider is an autogenerated mock type for the SessionProvider type
type MockSessionProvider struct {
	mock.Mock
}

type MockSessionProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionProvider) EXPECT() *MockSessionProvider_Expecter {
	return &MockSessionProvider_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function with given fields: ctx, assertion
func (_m *MockSessionProvider) CreateSession(ctx *gin.Context, assertion *saml.Assertion) error {
	ret := _m.Called(ctx, assertion)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *saml.Assertion) error); ok {
		r0 = rf(ctx, assertion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionProvider_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionProvider_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx *gin.Context
//   - assertion *saml.Assertion
func (_e *MockSessionProvider_Expecter) CreateSession(ctx interface{}, assertion interface{}) *MockSessionProvider_CreateSession_Call {
	return &MockSessionProvider_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, assertion)}
}

func (_c *MockSessionProvider_CreateSession_Call) Run(run func(ctx *gin.Context, assertion *saml.Assertion)) *MockSessionProvider_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(*saml.Assertion))
	})
	return _c
}

func (_c *MockSessionProvider_CreateSession_Call) Return(_a0 error) *MockSessionProvider_CreateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionProvider_CreateSession_Call) RunAndReturn(run func(*gin.Context, *saml.Assertion) error) *MockSessionProvider_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function with given fields: ctx
func (_m *MockSessionProvider) DeleteSession(ctx *gin.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionProvider_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockSessionProvider_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockSessionProvider_Expecter) DeleteSession(ctx interface{}) *MockSessionProvider_DeleteSession_Call {
	return &MockSessionProvider_DeleteSession_Call{Call: _e.mock.On("DeleteSession", ctx)}
}

func (_c *MockSessionProvider_DeleteSession_Call) Run(run func(ctx *gin.Context)) *MockSessionProvider_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockSessionProvider_DeleteSession_Call) Return(_a0 error) *MockSessionProvider_DeleteSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionProvider_DeleteSession_Call) RunAndReturn(run func(*gin.Context) error) *MockSessionProvider_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetCodec provides a mock function with no fields
func (_m *MockSessionProvider) GetCodec() samlsp.SessionCodec {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCodec")
	}

	var r0 samlsp.SessionCodec
	if rf, ok := ret.Get(0).(func() samlsp.SessionCodec); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(samlsp.SessionCodec)
		}
	}

	return r0
}

// MockSessionProvider_GetCodec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCodec'
type MockSessionProvider_GetCodec_Call struct {
	*mock.Call
}

// GetCodec is a helper method to define mock.On call
func (_e *MockSessionProvider_Expecter) GetCodec() *MockSessionProvider_GetCodec_Call {
	return &MockSessionProvider_GetCodec_Call{Call: _e.mock.On("GetCodec")}
}

func (_c *MockSessionProvider_GetCodec_Call) Run(run func()) *MockSessionProvider_GetCodec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionProvider_GetCodec_Call) Return(_a0 samlsp.SessionCodec) *MockSessionProvider_GetCodec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionProvider_GetCodec_Call) RunAndReturn(run func() samlsp.SessionCodec) *MockSessionProvider_GetCodec_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaxAge provides a mock function with no fields
func (_m *MockSessionProvider) GetMaxAge() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMaxAge")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// MockSessionProvider_GetMaxAge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxAge'
type MockSessionProvider_GetMaxAge_Call struct {
	*mock.Call
}

// GetMaxAge is a helper method to define mock.On call
func (_e *MockSessionProvider_Expecter) GetMaxAge() *MockSessionProvider_GetMaxAge_Call {
	return &MockSessionProvider_GetMaxAge_Call{Call: _e.mock.On("GetMaxAge")}
}

func (_c *MockSessionProvider_GetMaxAge_Call) Run(run func()) *MockSessionProvider_GetMaxAge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionProvider_GetMaxAge_Call) Return(_a0 time.Duration) *MockSessionProvider_GetMaxAge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionProvider_GetMaxAge_Call) RunAndReturn(run func() time.Duration) *MockSessionProvider_GetMaxAge_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with no fields
func (_m *MockSessionProvider) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockSessionProvider_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockSessionProvider_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockSessionProvider_Expecter) GetName() *MockSessionProvider_GetName_Call {
	return &MockSessionProvider_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockSessionProvider_GetName_Call) Run(run func()) *MockSessionProvider_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionProvider_GetName_Call) Return(_a0 string) *MockSessionProvider_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionProvider_GetName_Call) RunAndReturn(run func() string) *MockSessionProvider_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: ctx
func (_m *MockSessionProvider) GetSession(ctx *gin.Context) (samlsp.Session, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 samlsp.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (samlsp.Session, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) samlsp.Session); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(samlsp.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionProvider_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockSessionProvider_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockSessionProvider_Expecter) GetSession(ctx interface{}) *MockSessionProvider_GetSession_Call {
	return &MockSessionProvider_GetSession_Call{Call: _e.mock.On("GetSession", ctx)}
}

func (_c *MockSessionProvider_GetSession_Call) Run(run func(ctx *gin.Context)) *MockSessionProvider_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockSessionProvider_GetSession_Call) Return(_a0 samlsp.Session, _a1 error) *MockSessionProvider_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionProvider_GetSession_Call) RunAndReturn(run func(*gin.Context) (samlsp.Session, error)) *MockSessionProvider_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// SetCodec provides a mock function with given fields: codec
func (_m *MockSessionProvider) SetCodec(codec samlsp.SessionCodec) {
	_m.Called(codec)
}

// MockSessionProvider_SetCodec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCodec'
type MockSessionProvider_SetCodec_Call struct {
	*mock.Call
}

// SetCodec is a helper method to define mock.On call
//   - codec samlsp.SessionCodec
func (_e *MockSessionProvider_Expecter) SetCodec(codec interface{}) *MockSessionProvider_SetCodec_Call {
	return &MockSessionProvider_SetCodec_Call{Call: _e.mock.On("SetCodec", codec)}
}

func (_c *MockSessionProvider_SetCodec_Call) Run(run func(codec samlsp.SessionCodec)) *MockSessionProvider_SetCodec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(samlsp.SessionCodec))
	})
	return _c
}

func (_c *MockSessionProvider_SetCodec_Call) Return() *MockSessionProvider_SetCodec_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionProvider_SetCodec_Call) RunAndReturn(run func(samlsp.SessionCodec)) *MockSessionProvider_SetCodec_Call {
	_c.Run(run)
	return _c
}

// SetMaxAge provides a mock function with given fields: age
func (_m *MockSessionProvider) SetMaxAge(age time.Duration) {
	_m.Called(age)
}

// MockSessionProvider_SetMaxAge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMaxAge'
type MockSessionProvider_SetMaxAge_Call struct {
	*mock.Call
}

// SetMaxAge is a helper method to define mock.On call
//   - age time.Duration
func (_e *MockSessionProvider_Expecter) SetMaxAge(age interface{}) *MockSessionProvider_SetMaxAge_Call {
	return &MockSessionProvider_SetMaxAge_Call{Call: _e.mock.On("SetMaxAge", age)}
}

func (_c *MockSessionProvider_SetMaxAge_Call) Run(run func(age time.Duration)) *MockSessionProvider_SetMaxAge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *MockSessionProvider_SetMaxAge_Call) Return() *MockSessionProvider_SetMaxAge_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionProvider_SetMaxAge_Call) RunAndReturn(run func(time.Duration)) *MockSessionProvider_SetMaxAge_Call {
	_c.Run(run)
	return _c
}

// SetName provides a mock function with given fields: name
func (_m *MockSessionProvider) SetName(name string) {
	_m.Called(name)
}

// MockSessionProvider_SetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetName'
type MockSessionProvider_SetName_Call struct {
	*mock.Call
}

// SetName is a helper method to define mock.On call
//   - name string
func (_e *MockSessionProvider_Expecter) SetName(name interface{}) *MockSessionProvider_SetName_Call {
	return &MockSessionProvider_SetName_Call{Call: _e.mock.On("SetName", name)}
}

func (_c *MockSessionProvider_SetName_Call) Run(run func(name string)) *MockSessionProvider_SetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSessionProvider_SetName_Call) Return() *MockSessionProvider_SetName_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionProvider_SetName_Call) RunAndReturn(run func(string)) *MockSessionProvider_SetName_Call {
	_c.Run(run)
	return _c
}

// NewMockSessionProvider creates a new instance of MockSessionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionProvider {
	mock := &MockSessionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
