// Code generated by mockery. DO NOT EDIT.

package samlsp

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockErrorFunction is an autogenerated mock type for the ErrorFunction type
type MockErrorFunction struct {
	mock.Mock
}

type MockErrorFunction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorFunction) EXPECT() *MockErrorFunction_Expecter {
	return &MockErrorFunction_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: w, r, err
func (_m *MockErrorFunction) Execute(w http.ResponseWriter, r *http.Request, err error) {
	_m.Called(w, r, err)
}

// MockErrorFunction_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockErrorFunction_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - err error
func (_e *MockErrorFunction_Expecter) Execute(w interface{}, r interface{}, err interface{}) *MockErrorFunction_Execute_Call {
	return &MockErrorFunction_Execute_Call{Call: _e.mock.On("Execute", w, r, err)}
}

func (_c *MockErrorFunction_Execute_Call) Run(run func(w http.ResponseWriter, r *http.Request, err error)) *MockErrorFunction_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request), args[2].(error))
	})
	return _c
}

func (_c *MockErrorFunction_Execute_Call) Return() *MockErrorFunction_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockErrorFunction_Execute_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request, error)) *MockErrorFunction_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockErrorFunction creates a new instance of MockErrorFunction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockErrorFunction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockErrorFunction {
	mock := &MockErrorFunction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
