// Code generated by mockery. DO NOT EDIT.

package samlsp

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	saml "github.com/adalundhe/saml-gin"

	samlsp "github.com/adalundhe/saml-gin/samlsp"
)

// MockMiddleware is an autogenerated mock type for the Middleware type
type MockMiddleware struct {
	mock.Mock
}

type MockMiddleware_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMiddleware) EXPECT() *MockMiddleware_Expecter {
	return &MockMiddleware_Expecter{mock: &_m.Mock}
}

// CreateSessionFromAssertion provides a mock function with given fields: c, assertion, redirectURI
func (_m *MockMiddleware) CreateSessionFromAssertion(c *gin.Context, assertion *saml.Assertion, redirectURI string) (string, error) {
	ret := _m.Called(c, assertion, redirectURI)

	if len(ret) == 0 {
		panic("no return value specified for CreateSessionFromAssertion")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context, *saml.Assertion, string) (string, error)); ok {
		return rf(c, assertion, redirectURI)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *saml.Assertion, string) string); ok {
		r0 = rf(c, assertion, redirectURI)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *saml.Assertion, string) error); ok {
		r1 = rf(c, assertion, redirectURI)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMiddleware_CreateSessionFromAssertion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSessionFromAssertion'
type MockMiddleware_CreateSessionFromAssertion_Call struct {
	*mock.Call
}

// CreateSessionFromAssertion is a helper method to define mock.On call
//   - c *gin.Context
//   - assertion *saml.Assertion
//   - redirectURI string
func (_e *MockMiddleware_Expecter) CreateSessionFromAssertion(c interface{}, assertion interface{}, redirectURI interface{}) *MockMiddleware_CreateSessionFromAssertion_Call {
	return &MockMiddleware_CreateSessionFromAssertion_Call{Call: _e.mock.On("CreateSessionFromAssertion", c, assertion, redirectURI)}
}

func (_c *MockMiddleware_CreateSessionFromAssertion_Call) Run(run func(c *gin.Context, assertion *saml.Assertion, redirectURI string)) *MockMiddleware_CreateSessionFromAssertion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(*saml.Assertion), args[2].(string))
	})
	return _c
}

func (_c *MockMiddleware_CreateSessionFromAssertion_Call) Return(_a0 string, _a1 error) *MockMiddleware_CreateSessionFromAssertion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMiddleware_CreateSessionFromAssertion_Call) RunAndReturn(run func(*gin.Context, *saml.Assertion, string) (string, error)) *MockMiddleware_CreateSessionFromAssertion_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestTracker provides a mock function with no fields
func (_m *MockMiddleware) GetRequestTracker() samlsp.RequestTracker {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRequestTracker")
	}

	var r0 samlsp.RequestTracker
	if rf, ok := ret.Get(0).(func() samlsp.RequestTracker); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(samlsp.RequestTracker)
		}
	}

	return r0
}

// MockMiddleware_GetRequestTracker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestTracker'
type MockMiddleware_GetRequestTracker_Call struct {
	*mock.Call
}

// GetRequestTracker is a helper method to define mock.On call
func (_e *MockMiddleware_Expecter) GetRequestTracker() *MockMiddleware_GetRequestTracker_Call {
	return &MockMiddleware_GetRequestTracker_Call{Call: _e.mock.On("GetRequestTracker")}
}

func (_c *MockMiddleware_GetRequestTracker_Call) Run(run func()) *MockMiddleware_GetRequestTracker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMiddleware_GetRequestTracker_Call) Return(_a0 samlsp.RequestTracker) *MockMiddleware_GetRequestTracker_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMiddleware_GetRequestTracker_Call) RunAndReturn(run func() samlsp.RequestTracker) *MockMiddleware_GetRequestTracker_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceProvider provides a mock function with no fields
func (_m *MockMiddleware) GetServiceProvider() saml.ServiceProvider {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetServiceProvider")
	}

	var r0 saml.ServiceProvider
	if rf, ok := ret.Get(0).(func() saml.ServiceProvider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(saml.ServiceProvider)
		}
	}

	return r0
}

// MockMiddleware_GetServiceProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceProvider'
type MockMiddleware_GetServiceProvider_Call struct {
	*mock.Call
}

// GetServiceProvider is a helper method to define mock.On call
func (_e *MockMiddleware_Expecter) GetServiceProvider() *MockMiddleware_GetServiceProvider_Call {
	return &MockMiddleware_GetServiceProvider_Call{Call: _e.mock.On("GetServiceProvider")}
}

func (_c *MockMiddleware_GetServiceProvider_Call) Run(run func()) *MockMiddleware_GetServiceProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMiddleware_GetServiceProvider_Call) Return(_a0 saml.ServiceProvider) *MockMiddleware_GetServiceProvider_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMiddleware_GetServiceProvider_Call) RunAndReturn(run func() saml.ServiceProvider) *MockMiddleware_GetServiceProvider_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with no fields
func (_m *MockMiddleware) GetSession() samlsp.SessionProvider {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 samlsp.SessionProvider
	if rf, ok := ret.Get(0).(func() samlsp.SessionProvider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(samlsp.SessionProvider)
		}
	}

	return r0
}

// MockMiddleware_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockMiddleware_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
func (_e *MockMiddleware_Expecter) GetSession() *MockMiddleware_GetSession_Call {
	return &MockMiddleware_GetSession_Call{Call: _e.mock.On("GetSession")}
}

func (_c *MockMiddleware_GetSession_Call) Run(run func()) *MockMiddleware_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMiddleware_GetSession_Call) Return(_a0 samlsp.SessionProvider) *MockMiddleware_GetSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMiddleware_GetSession_Call) RunAndReturn(run func() samlsp.SessionProvider) *MockMiddleware_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// HandleStartAuthFlow provides a mock function with given fields: c
func (_m *MockMiddleware) HandleStartAuthFlow(c *gin.Context) {
	_m.Called(c)
}

// MockMiddleware_HandleStartAuthFlow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleStartAuthFlow'
type MockMiddleware_HandleStartAuthFlow_Call struct {
	*mock.Call
}

// HandleStartAuthFlow is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockMiddleware_Expecter) HandleStartAuthFlow(c interface{}) *MockMiddleware_HandleStartAuthFlow_Call {
	return &MockMiddleware_HandleStartAuthFlow_Call{Call: _e.mock.On("HandleStartAuthFlow", c)}
}

func (_c *MockMiddleware_HandleStartAuthFlow_Call) Run(run func(c *gin.Context)) *MockMiddleware_HandleStartAuthFlow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockMiddleware_HandleStartAuthFlow_Call) Return() *MockMiddleware_HandleStartAuthFlow_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMiddleware_HandleStartAuthFlow_Call) RunAndReturn(run func(*gin.Context)) *MockMiddleware_HandleStartAuthFlow_Call {
	_c.Run(run)
	return _c
}

// RequireAccount provides a mock function with no fields
func (_m *MockMiddleware) RequireAccount() gin.HandlerFunc {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequireAccount")
	}

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// MockMiddleware_RequireAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireAccount'
type MockMiddleware_RequireAccount_Call struct {
	*mock.Call
}

// RequireAccount is a helper method to define mock.On call
func (_e *MockMiddleware_Expecter) RequireAccount() *MockMiddleware_RequireAccount_Call {
	return &MockMiddleware_RequireAccount_Call{Call: _e.mock.On("RequireAccount")}
}

func (_c *MockMiddleware_RequireAccount_Call) Run(run func()) *MockMiddleware_RequireAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMiddleware_RequireAccount_Call) Return(_a0 gin.HandlerFunc) *MockMiddleware_RequireAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMiddleware_RequireAccount_Call) RunAndReturn(run func() gin.HandlerFunc) *MockMiddleware_RequireAccount_Call {
	_c.Call.Return(run)
	return _c
}

// ServeACS provides a mock function with given fields: c
func (_m *MockMiddleware) ServeACS(c *gin.Context) (string, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ServeACS")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (string, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMiddleware_ServeACS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeACS'
type MockMiddleware_ServeACS_Call struct {
	*mock.Call
}

// ServeACS is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockMiddleware_Expecter) ServeACS(c interface{}) *MockMiddleware_ServeACS_Call {
	return &MockMiddleware_ServeACS_Call{Call: _e.mock.On("ServeACS", c)}
}

func (_c *MockMiddleware_ServeACS_Call) Run(run func(c *gin.Context)) *MockMiddleware_ServeACS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockMiddleware_ServeACS_Call) Return(_a0 string, _a1 error) *MockMiddleware_ServeACS_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMiddleware_ServeACS_Call) RunAndReturn(run func(*gin.Context) (string, error)) *MockMiddleware_ServeACS_Call {
	_c.Call.Return(run)
	return _c
}

// ServeMetadata provides a mock function with given fields: c
func (_m *MockMiddleware) ServeMetadata(c *gin.Context) ([]byte, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ServeMetadata")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) ([]byte, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) []byte); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMiddleware_ServeMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeMetadata'
type MockMiddleware_ServeMetadata_Call struct {
	*mock.Call
}

// ServeMetadata is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockMiddleware_Expecter) ServeMetadata(c interface{}) *MockMiddleware_ServeMetadata_Call {
	return &MockMiddleware_ServeMetadata_Call{Call: _e.mock.On("ServeMetadata", c)}
}

func (_c *MockMiddleware_ServeMetadata_Call) Run(run func(c *gin.Context)) *MockMiddleware_ServeMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockMiddleware_ServeMetadata_Call) Return(_a0 []byte, _a1 error) *MockMiddleware_ServeMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMiddleware_ServeMetadata_Call) RunAndReturn(run func(*gin.Context) ([]byte, error)) *MockMiddleware_ServeMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// SetOnError provides a mock function with given fields: onErr
func (_m *MockMiddleware) SetOnError(onErr func(*gin.Context, error) error) {
	_m.Called(onErr)
}

// MockMiddleware_SetOnError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOnError'
type MockMiddleware_SetOnError_Call struct {
	*mock.Call
}

// SetOnError is a helper method to define mock.On call
//   - onErr func(*gin.Context , error) error
func (_e *MockMiddleware_Expecter) SetOnError(onErr interface{}) *MockMiddleware_SetOnError_Call {
	return &MockMiddleware_SetOnError_Call{Call: _e.mock.On("SetOnError", onErr)}
}

func (_c *MockMiddleware_SetOnError_Call) Run(run func(onErr func(*gin.Context, error) error)) *MockMiddleware_SetOnError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(*gin.Context, error) error))
	})
	return _c
}

func (_c *MockMiddleware_SetOnError_Call) Return() *MockMiddleware_SetOnError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMiddleware_SetOnError_Call) RunAndReturn(run func(func(*gin.Context, error) error)) *MockMiddleware_SetOnError_Call {
	_c.Run(run)
	return _c
}

// SetRequestTracker provides a mock function with given fields: tracker
func (_m *MockMiddleware) SetRequestTracker(tracker samlsp.RequestTracker) {
	_m.Called(tracker)
}

// MockMiddleware_SetRequestTracker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRequestTracker'
type MockMiddleware_SetRequestTracker_Call struct {
	*mock.Call
}

// SetRequestTracker is a helper method to define mock.On call
//   - tracker samlsp.RequestTracker
func (_e *MockMiddleware_Expecter) SetRequestTracker(tracker interface{}) *MockMiddleware_SetRequestTracker_Call {
	return &MockMiddleware_SetRequestTracker_Call{Call: _e.mock.On("SetRequestTracker", tracker)}
}

func (_c *MockMiddleware_SetRequestTracker_Call) Run(run func(tracker samlsp.RequestTracker)) *MockMiddleware_SetRequestTracker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(samlsp.RequestTracker))
	})
	return _c
}

func (_c *MockMiddleware_SetRequestTracker_Call) Return() *MockMiddleware_SetRequestTracker_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMiddleware_SetRequestTracker_Call) RunAndReturn(run func(samlsp.RequestTracker)) *MockMiddleware_SetRequestTracker_Call {
	_c.Run(run)
	return _c
}

// SetServiceProvider provides a mock function with given fields: sp
func (_m *MockMiddleware) SetServiceProvider(sp saml.ServiceProvider) {
	_m.Called(sp)
}

// MockMiddleware_SetServiceProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetServiceProvider'
type MockMiddleware_SetServiceProvider_Call struct {
	*mock.Call
}

// SetServiceProvider is a helper method to define mock.On call
//   - sp saml.ServiceProvider
func (_e *MockMiddleware_Expecter) SetServiceProvider(sp interface{}) *MockMiddleware_SetServiceProvider_Call {
	return &MockMiddleware_SetServiceProvider_Call{Call: _e.mock.On("SetServiceProvider", sp)}
}

func (_c *MockMiddleware_SetServiceProvider_Call) Run(run func(sp saml.ServiceProvider)) *MockMiddleware_SetServiceProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(saml.ServiceProvider))
	})
	return _c
}

func (_c *MockMiddleware_SetServiceProvider_Call) Return() *MockMiddleware_SetServiceProvider_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMiddleware_SetServiceProvider_Call) RunAndReturn(run func(saml.ServiceProvider)) *MockMiddleware_SetServiceProvider_Call {
	_c.Run(run)
	return _c
}

// SetSession provides a mock function with given fields: session
func (_m *MockMiddleware) SetSession(session samlsp.SessionProvider) {
	_m.Called(session)
}

// MockMiddleware_SetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSession'
type MockMiddleware_SetSession_Call struct {
	*mock.Call
}

// SetSession is a helper method to define mock.On call
//   - session samlsp.SessionProvider
func (_e *MockMiddleware_Expecter) SetSession(session interface{}) *MockMiddleware_SetSession_Call {
	return &MockMiddleware_SetSession_Call{Call: _e.mock.On("SetSession", session)}
}

func (_c *MockMiddleware_SetSession_Call) Run(run func(session samlsp.SessionProvider)) *MockMiddleware_SetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(samlsp.SessionProvider))
	})
	return _c
}

func (_c *MockMiddleware_SetSession_Call) Return() *MockMiddleware_SetSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMiddleware_SetSession_Call) RunAndReturn(run func(samlsp.SessionProvider)) *MockMiddleware_SetSession_Call {
	_c.Run(run)
	return _c
}

// NewMockMiddleware creates a new instance of MockMiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMiddleware {
	mock := &MockMiddleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
