// Code generated by mockery. DO NOT EDIT.

package samlsp

import (
	samlsp "github.com/adalundhe/saml-gin/samlsp"
	mock "github.com/stretchr/testify/mock"
)

// MockTrackedRequestCodec is an autogenerated mock type for the TrackedRequestCodec type
type MockTrackedRequestCodec struct {
	mock.Mock
}

type MockTrackedRequestCodec_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrackedRequestCodec) EXPECT() *MockTrackedRequestCodec_Expecter {
	return &MockTrackedRequestCodec_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function with given fields: signed
func (_m *MockTrackedRequestCodec) Decode(signed string) (*samlsp.TrackedRequest, error) {
	ret := _m.Called(signed)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 *samlsp.TrackedRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*samlsp.TrackedRequest, error)); ok {
		return rf(signed)
	}
	if rf, ok := ret.Get(0).(func(string) *samlsp.TrackedRequest); ok {
		r0 = rf(signed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*samlsp.TrackedRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(signed)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTrackedRequestCodec_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockTrackedRequestCodec_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - signed string
func (_e *MockTrackedRequestCodec_Expecter) Decode(signed interface{}) *MockTrackedRequestCodec_Decode_Call {
	return &MockTrackedRequestCodec_Decode_Call{Call: _e.mock.On("Decode", signed)}
}

func (_c *MockTrackedRequestCodec_Decode_Call) Run(run func(signed string)) *MockTrackedRequestCodec_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTrackedRequestCodec_Decode_Call) Return(_a0 *samlsp.TrackedRequest, _a1 error) *MockTrackedRequestCodec_Decode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackedRequestCodec_Decode_Call) RunAndReturn(run func(string) (*samlsp.TrackedRequest, error)) *MockTrackedRequestCodec_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Encode provides a mock function with given fields: value
func (_m *MockTrackedRequestCodec) Encode(value samlsp.TrackedRequest) (string, error) {
	ret := _m.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(samlsp.TrackedRequest) (string, error)); ok {
		return rf(value)
	}
	if rf, ok := ret.Get(0).(func(samlsp.TrackedRequest) string); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(samlsp.TrackedRequest) error); ok {
		r1 = rf(value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTrackedRequestCodec_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type MockTrackedRequestCodec_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - value samlsp.TrackedRequest
func (_e *MockTrackedRequestCodec_Expecter) Encode(value interface{}) *MockTrackedRequestCodec_Encode_Call {
	return &MockTrackedRequestCodec_Encode_Call{Call: _e.mock.On("Encode", value)}
}

func (_c *MockTrackedRequestCodec_Encode_Call) Run(run func(value samlsp.TrackedRequest)) *MockTrackedRequestCodec_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(samlsp.TrackedRequest))
	})
	return _c
}

func (_c *MockTrackedRequestCodec_Encode_Call) Return(_a0 string, _a1 error) *MockTrackedRequestCodec_Encode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackedRequestCodec_Encode_Call) RunAndReturn(run func(samlsp.TrackedRequest) (string, error)) *MockTrackedRequestCodec_Encode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTrackedRequestCodec creates a new instance of MockTrackedRequestCodec. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrackedRequestCodec(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrackedRequestCodec {
	mock := &MockTrackedRequestCodec{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
