// Code generated by mockery. DO NOT EDIT.

package samlsp

import (
	saml "github.com/adalundhe/saml-gin"
	mock "github.com/stretchr/testify/mock"

	samlsp "github.com/adalundhe/saml-gin/samlsp"
)

// MockSessionCodec is an autogenerated mock type for the SessionCodec type
type MockSessionCodec struct {
	mock.Mock
}

type MockSessionCodec_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionCodec) EXPECT() *MockSessionCodec_Expecter {
	return &MockSessionCodec_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function with given fields: _a0
func (_m *MockSessionCodec) Decode(_a0 string) (samlsp.Session, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 samlsp.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (samlsp.Session, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) samlsp.Session); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(samlsp.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionCodec_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockSessionCodec_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - _a0 string
func (_e *MockSessionCodec_Expecter) Decode(_a0 interface{}) *MockSessionCodec_Decode_Call {
	return &MockSessionCodec_Decode_Call{Call: _e.mock.On("Decode", _a0)}
}

func (_c *MockSessionCodec_Decode_Call) Run(run func(_a0 string)) *MockSessionCodec_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSessionCodec_Decode_Call) Return(_a0 samlsp.Session, _a1 error) *MockSessionCodec_Decode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionCodec_Decode_Call) RunAndReturn(run func(string) (samlsp.Session, error)) *MockSessionCodec_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Encode provides a mock function with given fields: s
func (_m *MockSessionCodec) Encode(s samlsp.Session) (string, error) {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(samlsp.Session) (string, error)); ok {
		return rf(s)
	}
	if rf, ok := ret.Get(0).(func(samlsp.Session) string); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(samlsp.Session) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionCodec_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type MockSessionCodec_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - s samlsp.Session
func (_e *MockSessionCodec_Expecter) Encode(s interface{}) *MockSessionCodec_Encode_Call {
	return &MockSessionCodec_Encode_Call{Call: _e.mock.On("Encode", s)}
}

func (_c *MockSessionCodec_Encode_Call) Run(run func(s samlsp.Session)) *MockSessionCodec_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(samlsp.Session))
	})
	return _c
}

func (_c *MockSessionCodec_Encode_Call) Return(_a0 string, _a1 error) *MockSessionCodec_Encode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionCodec_Encode_Call) RunAndReturn(run func(samlsp.Session) (string, error)) *MockSessionCodec_Encode_Call {
	_c.Call.Return(run)
	return _c
}

// New provides a mock function with given fields: assertion
func (_m *MockSessionCodec) New(assertion *saml.Assertion) (samlsp.Session, error) {
	ret := _m.Called(assertion)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 samlsp.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(*saml.Assertion) (samlsp.Session, error)); ok {
		return rf(assertion)
	}
	if rf, ok := ret.Get(0).(func(*saml.Assertion) samlsp.Session); ok {
		r0 = rf(assertion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(samlsp.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(*saml.Assertion) error); ok {
		r1 = rf(assertion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionCodec_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockSessionCodec_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - assertion *saml.Assertion
func (_e *MockSessionCodec_Expecter) New(assertion interface{}) *MockSessionCodec_New_Call {
	return &MockSessionCodec_New_Call{Call: _e.mock.On("New", assertion)}
}

func (_c *MockSessionCodec_New_Call) Run(run func(assertion *saml.Assertion)) *MockSessionCodec_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*saml.Assertion))
	})
	return _c
}

func (_c *MockSessionCodec_New_Call) Return(_a0 samlsp.Session, _a1 error) *MockSessionCodec_New_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionCodec_New_Call) RunAndReturn(run func(*saml.Assertion) (samlsp.Session, error)) *MockSessionCodec_New_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionCodec creates a new instance of MockSessionCodec. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionCodec(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionCodec {
	mock := &MockSessionCodec{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
