// Code generated by mockery. DO NOT EDIT.

package logger

import mock "github.com/stretchr/testify/mock"

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// Fatal provides a mock function with given fields: v
func (_m *MockInterface) Fatal(v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// MockInterface_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockInterface_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - v ...interface{}
func (_e *MockInterface_Expecter) Fatal(v ...interface{}) *MockInterface_Fatal_Call {
	return &MockInterface_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{}, v...)...)}
}

func (_c *MockInterface_Fatal_Call) Run(run func(v ...interface{})) *MockInterface_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockInterface_Fatal_Call) Return() *MockInterface_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInterface_Fatal_Call) RunAndReturn(run func(...interface{})) *MockInterface_Fatal_Call {
	_c.Run(run)
	return _c
}

// Fatalf provides a mock function with given fields: format, v
func (_m *MockInterface) Fatalf(format string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// MockInterface_Fatalf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatalf'
type MockInterface_Fatalf_Call struct {
	*mock.Call
}

// Fatalf is a helper method to define mock.On call
//   - format string
//   - v ...interface{}
func (_e *MockInterface_Expecter) Fatalf(format interface{}, v ...interface{}) *MockInterface_Fatalf_Call {
	return &MockInterface_Fatalf_Call{Call: _e.mock.On("Fatalf",
		append([]interface{}{format}, v...)...)}
}

func (_c *MockInterface_Fatalf_Call) Run(run func(format string, v ...interface{})) *MockInterface_Fatalf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockInterface_Fatalf_Call) Return() *MockInterface_Fatalf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInterface_Fatalf_Call) RunAndReturn(run func(string, ...interface{})) *MockInterface_Fatalf_Call {
	_c.Run(run)
	return _c
}

// Fatalln provides a mock function with given fields: v
func (_m *MockInterface) Fatalln(v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// MockInterface_Fatalln_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatalln'
type MockInterface_Fatalln_Call struct {
	*mock.Call
}

// Fatalln is a helper method to define mock.On call
//   - v ...interface{}
func (_e *MockInterface_Expecter) Fatalln(v ...interface{}) *MockInterface_Fatalln_Call {
	return &MockInterface_Fatalln_Call{Call: _e.mock.On("Fatalln",
		append([]interface{}{}, v...)...)}
}

func (_c *MockInterface_Fatalln_Call) Run(run func(v ...interface{})) *MockInterface_Fatalln_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockInterface_Fatalln_Call) Return() *MockInterface_Fatalln_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInterface_Fatalln_Call) RunAndReturn(run func(...interface{})) *MockInterface_Fatalln_Call {
	_c.Run(run)
	return _c
}

// Panic provides a mock function with given fields: v
func (_m *MockInterface) Panic(v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// MockInterface_Panic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panic'
type MockInterface_Panic_Call struct {
	*mock.Call
}

// Panic is a helper method to define mock.On call
//   - v ...interface{}
func (_e *MockInterface_Expecter) Panic(v ...interface{}) *MockInterface_Panic_Call {
	return &MockInterface_Panic_Call{Call: _e.mock.On("Panic",
		append([]interface{}{}, v...)...)}
}

func (_c *MockInterface_Panic_Call) Run(run func(v ...interface{})) *MockInterface_Panic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockInterface_Panic_Call) Return() *MockInterface_Panic_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInterface_Panic_Call) RunAndReturn(run func(...interface{})) *MockInterface_Panic_Call {
	_c.Run(run)
	return _c
}

// Panicf provides a mock function with given fields: format, v
func (_m *MockInterface) Panicf(format string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// MockInterface_Panicf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panicf'
type MockInterface_Panicf_Call struct {
	*mock.Call
}

// Panicf is a helper method to define mock.On call
//   - format string
//   - v ...interface{}
func (_e *MockInterface_Expecter) Panicf(format interface{}, v ...interface{}) *MockInterface_Panicf_Call {
	return &MockInterface_Panicf_Call{Call: _e.mock.On("Panicf",
		append([]interface{}{format}, v...)...)}
}

func (_c *MockInterface_Panicf_Call) Run(run func(format string, v ...interface{})) *MockInterface_Panicf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockInterface_Panicf_Call) Return() *MockInterface_Panicf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInterface_Panicf_Call) RunAndReturn(run func(string, ...interface{})) *MockInterface_Panicf_Call {
	_c.Run(run)
	return _c
}

// Panicln provides a mock function with given fields: v
func (_m *MockInterface) Panicln(v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// MockInterface_Panicln_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Panicln'
type MockInterface_Panicln_Call struct {
	*mock.Call
}

// Panicln is a helper method to define mock.On call
//   - v ...interface{}
func (_e *MockInterface_Expecter) Panicln(v ...interface{}) *MockInterface_Panicln_Call {
	return &MockInterface_Panicln_Call{Call: _e.mock.On("Panicln",
		append([]interface{}{}, v...)...)}
}

func (_c *MockInterface_Panicln_Call) Run(run func(v ...interface{})) *MockInterface_Panicln_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockInterface_Panicln_Call) Return() *MockInterface_Panicln_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInterface_Panicln_Call) RunAndReturn(run func(...interface{})) *MockInterface_Panicln_Call {
	_c.Run(run)
	return _c
}

// Print provides a mock function with given fields: v
func (_m *MockInterface) Print(v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// MockInterface_Print_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Print'
type MockInterface_Print_Call struct {
	*mock.Call
}

// Print is a helper method to define mock.On call
//   - v ...interface{}
func (_e *MockInterface_Expecter) Print(v ...interface{}) *MockInterface_Print_Call {
	return &MockInterface_Print_Call{Call: _e.mock.On("Print",
		append([]interface{}{}, v...)...)}
}

func (_c *MockInterface_Print_Call) Run(run func(v ...interface{})) *MockInterface_Print_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockInterface_Print_Call) Return() *MockInterface_Print_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInterface_Print_Call) RunAndReturn(run func(...interface{})) *MockInterface_Print_Call {
	_c.Run(run)
	return _c
}

// Printf provides a mock function with given fields: format, v
func (_m *MockInterface) Printf(format string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// MockInterface_Printf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Printf'
type MockInterface_Printf_Call struct {
	*mock.Call
}

// Printf is a helper method to define mock.On call
//   - format string
//   - v ...interface{}
func (_e *MockInterface_Expecter) Printf(format interface{}, v ...interface{}) *MockInterface_Printf_Call {
	return &MockInterface_Printf_Call{Call: _e.mock.On("Printf",
		append([]interface{}{format}, v...)...)}
}

func (_c *MockInterface_Printf_Call) Run(run func(format string, v ...interface{})) *MockInterface_Printf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockInterface_Printf_Call) Return() *MockInterface_Printf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInterface_Printf_Call) RunAndReturn(run func(string, ...interface{})) *MockInterface_Printf_Call {
	_c.Run(run)
	return _c
}

// Println provides a mock function with given fields: v
func (_m *MockInterface) Println(v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// MockInterface_Println_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Println'
type MockInterface_Println_Call struct {
	*mock.Call
}

// Println is a helper method to define mock.On call
//   - v ...interface{}
func (_e *MockInterface_Expecter) Println(v ...interface{}) *MockInterface_Println_Call {
	return &MockInterface_Println_Call{Call: _e.mock.On("Println",
		append([]interface{}{}, v...)...)}
}

func (_c *MockInterface_Println_Call) Run(run func(v ...interface{})) *MockInterface_Println_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockInterface_Println_Call) Return() *MockInterface_Println_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInterface_Println_Call) RunAndReturn(run func(...interface{})) *MockInterface_Println_Call {
	_c.Run(run)
	return _c
}

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
