// Code generated by mockery. DO NOT EDIT.

package samlidp

import mock "github.com/stretchr/testify/mock"

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: key
func (_m *MockStore) Delete(key string) error {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key string
func (_e *MockStore_Expecter) Delete(key interface{}) *MockStore_Delete_Call {
	return &MockStore_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *MockStore_Delete_Call) Run(run func(key string)) *MockStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStore_Delete_Call) Return(_a0 error) *MockStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Delete_Call) RunAndReturn(run func(string) error) *MockStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key, value
func (_m *MockStore) Get(key string, value interface{}) error {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
//   - value interface{}
func (_e *MockStore_Expecter) Get(key interface{}, value interface{}) *MockStore_Get_Call {
	return &MockStore_Get_Call{Call: _e.mock.On("Get", key, value)}
}

func (_c *MockStore_Get_Call) Run(run func(key string, value interface{})) *MockStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *MockStore_Get_Call) Return(_a0 error) *MockStore_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Get_Call) RunAndReturn(run func(string, interface{}) error) *MockStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: prefix
func (_m *MockStore) List(prefix string) ([]string, error) {
	ret := _m.Called(prefix)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(prefix)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(prefix)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - prefix string
func (_e *MockStore_Expecter) List(prefix interface{}) *MockStore_List_Call {
	return &MockStore_List_Call{Call: _e.mock.On("List", prefix)}
}

func (_c *MockStore_List_Call) Run(run func(prefix string)) *MockStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStore_List_Call) Return(_a0 []string, _a1 error) *MockStore_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_List_Call) RunAndReturn(run func(string) ([]string, error)) *MockStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: key, value
func (_m *MockStore) Put(key string, value interface{}) error {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - key string
//   - value interface{}
func (_e *MockStore_Expecter) Put(key interface{}, value interface{}) *MockStore_Put_Call {
	return &MockStore_Put_Call{Call: _e.mock.On("Put", key, value)}
}

func (_c *MockStore_Put_Call) Run(run func(key string, value interface{})) *MockStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *MockStore_Put_Call) Return(_a0 error) *MockStore_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Put_Call) RunAndReturn(run func(string, interface{}) error) *MockStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
