// Code generated by mockery. DO NOT EDIT.

package xmlenc

import (
	etree "github.com/beevik/etree"
	mock "github.com/stretchr/testify/mock"
)

// MockDecrypter is an autogenerated mock type for the Decrypter type
type MockDecrypter struct {
	mock.Mock
}

type MockDecrypter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDecrypter) EXPECT() *MockDecrypter_Expecter {
	return &MockDecrypter_Expecter{mock: &_m.Mock}
}

// Algorithm provides a mock function with no fields
func (_m *MockDecrypter) Algorithm() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Algorithm")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDecrypter_Algorithm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Algorithm'
type MockDecrypter_Algorithm_Call struct {
	*mock.Call
}

// Algorithm is a helper method to define mock.On call
func (_e *MockDecrypter_Expecter) Algorithm() *MockDecrypter_Algorithm_Call {
	return &MockDecrypter_Algorithm_Call{Call: _e.mock.On("Algorithm")}
}

func (_c *MockDecrypter_Algorithm_Call) Run(run func()) *MockDecrypter_Algorithm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDecrypter_Algorithm_Call) Return(_a0 string) *MockDecrypter_Algorithm_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDecrypter_Algorithm_Call) RunAndReturn(run func() string) *MockDecrypter_Algorithm_Call {
	_c.Call.Return(run)
	return _c
}

// Decrypt provides a mock function with given fields: key, ciphertextEl
func (_m *MockDecrypter) Decrypt(key interface{}, ciphertextEl *etree.Element) ([]byte, error) {
	ret := _m.Called(key, ciphertextEl)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, *etree.Element) ([]byte, error)); ok {
		return rf(key, ciphertextEl)
	}
	if rf, ok := ret.Get(0).(func(interface{}, *etree.Element) []byte); ok {
		r0 = rf(key, ciphertextEl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, *etree.Element) error); ok {
		r1 = rf(key, ciphertextEl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDecrypter_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockDecrypter_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - key interface{}
//   - ciphertextEl *etree.Element
func (_e *MockDecrypter_Expecter) Decrypt(key interface{}, ciphertextEl interface{}) *MockDecrypter_Decrypt_Call {
	return &MockDecrypter_Decrypt_Call{Call: _e.mock.On("Decrypt", key, ciphertextEl)}
}

func (_c *MockDecrypter_Decrypt_Call) Run(run func(key interface{}, ciphertextEl *etree.Element)) *MockDecrypter_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(*etree.Element))
	})
	return _c
}

func (_c *MockDecrypter_Decrypt_Call) Return(_a0 []byte, _a1 error) *MockDecrypter_Decrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDecrypter_Decrypt_Call) RunAndReturn(run func(interface{}, *etree.Element) ([]byte, error)) *MockDecrypter_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDecrypter creates a new instance of MockDecrypter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDecrypter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDecrypter {
	mock := &MockDecrypter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
