// Code generated by mockery. DO NOT EDIT.

package xmlenc

import (
	etree "github.com/beevik/etree"
	mock "github.com/stretchr/testify/mock"
)

// MockEncrypter is an autogenerated mock type for the Encrypter type
type MockEncrypter struct {
	mock.Mock
}

type MockEncrypter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEncrypter) EXPECT() *MockEncrypter_Expecter {
	return &MockEncrypter_Expecter{mock: &_m.Mock}
}

// Encrypt provides a mock function with given fields: key, plaintext, nonce
func (_m *MockEncrypter) Encrypt(key interface{}, plaintext []byte, nonce []byte) (*etree.Element, error) {
	ret := _m.Called(key, plaintext, nonce)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 *etree.Element
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, []byte, []byte) (*etree.Element, error)); ok {
		return rf(key, plaintext, nonce)
	}
	if rf, ok := ret.Get(0).(func(interface{}, []byte, []byte) *etree.Element); ok {
		r0 = rf(key, plaintext, nonce)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*etree.Element)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, []byte, []byte) error); ok {
		r1 = rf(key, plaintext, nonce)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEncrypter_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockEncrypter_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - key interface{}
//   - plaintext []byte
//   - nonce []byte
func (_e *MockEncrypter_Expecter) Encrypt(key interface{}, plaintext interface{}, nonce interface{}) *MockEncrypter_Encrypt_Call {
	return &MockEncrypter_Encrypt_Call{Call: _e.mock.On("Encrypt", key, plaintext, nonce)}
}

func (_c *MockEncrypter_Encrypt_Call) Run(run func(key interface{}, plaintext []byte, nonce []byte)) *MockEncrypter_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].([]byte), args[2].([]byte))
	})
	return _c
}

func (_c *MockEncrypter_Encrypt_Call) Return(_a0 *etree.Element, _a1 error) *MockEncrypter_Encrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEncrypter_Encrypt_Call) RunAndReturn(run func(interface{}, []byte, []byte) (*etree.Element, error)) *MockEncrypter_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEncrypter creates a new instance of MockEncrypter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEncrypter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEncrypter {
	mock := &MockEncrypter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
