// Code generated by mockery. DO NOT EDIT.

package xmlenc

import (
	etree "github.com/beevik/etree"
	mock "github.com/stretchr/testify/mock"
)

// MockBlockCipher is an autogenerated mock type for the BlockCipher type
type MockBlockCipher struct {
	mock.Mock
}

type MockBlockCipher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockCipher) EXPECT() *MockBlockCipher_Expecter {
	return &MockBlockCipher_Expecter{mock: &_m.Mock}
}

// Algorithm provides a mock function with no fields
func (_m *MockBlockCipher) Algorithm() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Algorithm")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockBlockCipher_Algorithm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Algorithm'
type MockBlockCipher_Algorithm_Call struct {
	*mock.Call
}

// Algorithm is a helper method to define mock.On call
func (_e *MockBlockCipher_Expecter) Algorithm() *MockBlockCipher_Algorithm_Call {
	return &MockBlockCipher_Algorithm_Call{Call: _e.mock.On("Algorithm")}
}

func (_c *MockBlockCipher_Algorithm_Call) Run(run func()) *MockBlockCipher_Algorithm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockCipher_Algorithm_Call) Return(_a0 string) *MockBlockCipher_Algorithm_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockCipher_Algorithm_Call) RunAndReturn(run func() string) *MockBlockCipher_Algorithm_Call {
	_c.Call.Return(run)
	return _c
}

// Decrypt provides a mock function with given fields: key, ciphertextEl
func (_m *MockBlockCipher) Decrypt(key interface{}, ciphertextEl *etree.Element) ([]byte, error) {
	ret := _m.Called(key, ciphertextEl)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, *etree.Element) ([]byte, error)); ok {
		return rf(key, ciphertextEl)
	}
	if rf, ok := ret.Get(0).(func(interface{}, *etree.Element) []byte); ok {
		r0 = rf(key, ciphertextEl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, *etree.Element) error); ok {
		r1 = rf(key, ciphertextEl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBlockCipher_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockBlockCipher_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - key interface{}
//   - ciphertextEl *etree.Element
func (_e *MockBlockCipher_Expecter) Decrypt(key interface{}, ciphertextEl interface{}) *MockBlockCipher_Decrypt_Call {
	return &MockBlockCipher_Decrypt_Call{Call: _e.mock.On("Decrypt", key, ciphertextEl)}
}

func (_c *MockBlockCipher_Decrypt_Call) Run(run func(key interface{}, ciphertextEl *etree.Element)) *MockBlockCipher_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(*etree.Element))
	})
	return _c
}

func (_c *MockBlockCipher_Decrypt_Call) Return(_a0 []byte, _a1 error) *MockBlockCipher_Decrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBlockCipher_Decrypt_Call) RunAndReturn(run func(interface{}, *etree.Element) ([]byte, error)) *MockBlockCipher_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function with given fields: key, plaintext, nonce
func (_m *MockBlockCipher) Encrypt(key interface{}, plaintext []byte, nonce []byte) (*etree.Element, error) {
	ret := _m.Called(key, plaintext, nonce)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 *etree.Element
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, []byte, []byte) (*etree.Element, error)); ok {
		return rf(key, plaintext, nonce)
	}
	if rf, ok := ret.Get(0).(func(interface{}, []byte, []byte) *etree.Element); ok {
		r0 = rf(key, plaintext, nonce)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*etree.Element)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, []byte, []byte) error); ok {
		r1 = rf(key, plaintext, nonce)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBlockCipher_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockBlockCipher_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - key interface{}
//   - plaintext []byte
//   - nonce []byte
func (_e *MockBlockCipher_Expecter) Encrypt(key interface{}, plaintext interface{}, nonce interface{}) *MockBlockCipher_Encrypt_Call {
	return &MockBlockCipher_Encrypt_Call{Call: _e.mock.On("Encrypt", key, plaintext, nonce)}
}

func (_c *MockBlockCipher_Encrypt_Call) Run(run func(key interface{}, plaintext []byte, nonce []byte)) *MockBlockCipher_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].([]byte), args[2].([]byte))
	})
	return _c
}

func (_c *MockBlockCipher_Encrypt_Call) Return(_a0 *etree.Element, _a1 error) *MockBlockCipher_Encrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBlockCipher_Encrypt_Call) RunAndReturn(run func(interface{}, []byte, []byte) (*etree.Element, error)) *MockBlockCipher_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// KeySize provides a mock function with no fields
func (_m *MockBlockCipher) KeySize() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for KeySize")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockBlockCipher_KeySize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeySize'
type MockBlockCipher_KeySize_Call struct {
	*mock.Call
}

// KeySize is a helper method to define mock.On call
func (_e *MockBlockCipher_Expecter) KeySize() *MockBlockCipher_KeySize_Call {
	return &MockBlockCipher_KeySize_Call{Call: _e.mock.On("KeySize")}
}

func (_c *MockBlockCipher_KeySize_Call) Run(run func()) *MockBlockCipher_KeySize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockCipher_KeySize_Call) Return(_a0 int) *MockBlockCipher_KeySize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockCipher_KeySize_Call) RunAndReturn(run func() int) *MockBlockCipher_KeySize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBlockCipher creates a new instance of MockBlockCipher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockCipher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockCipher {
	mock := &MockBlockCipher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
