// Code generated by mockery. DO NOT EDIT.

package xmlenc

import (
	hash "hash"

	mock "github.com/stretchr/testify/mock"
)

// MockDigestMethod is an autogenerated mock type for the DigestMethod type
type MockDigestMethod struct {
	mock.Mock
}

type MockDigestMethod_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDigestMethod) EXPECT() *MockDigestMethod_Expecter {
	return &MockDigestMethod_Expecter{mock: &_m.Mock}
}

// Algorithm provides a mock function with no fields
func (_m *MockDigestMethod) Algorithm() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Algorithm")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDigestMethod_Algorithm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Algorithm'
type MockDigestMethod_Algorithm_Call struct {
	*mock.Call
}

// Algorithm is a helper method to define mock.On call
func (_e *MockDigestMethod_Expecter) Algorithm() *MockDigestMethod_Algorithm_Call {
	return &MockDigestMethod_Algorithm_Call{Call: _e.mock.On("Algorithm")}
}

func (_c *MockDigestMethod_Algorithm_Call) Run(run func()) *MockDigestMethod_Algorithm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDigestMethod_Algorithm_Call) Return(_a0 string) *MockDigestMethod_Algorithm_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDigestMethod_Algorithm_Call) RunAndReturn(run func() string) *MockDigestMethod_Algorithm_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function with no fields
func (_m *MockDigestMethod) Hash() hash.Hash {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 hash.Hash
	if rf, ok := ret.Get(0).(func() hash.Hash); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(hash.Hash)
		}
	}

	return r0
}

// MockDigestMethod_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockDigestMethod_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
func (_e *MockDigestMethod_Expecter) Hash() *MockDigestMethod_Hash_Call {
	return &MockDigestMethod_Hash_Call{Call: _e.mock.On("Hash")}
}

func (_c *MockDigestMethod_Hash_Call) Run(run func()) *MockDigestMethod_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDigestMethod_Hash_Call) Return(_a0 hash.Hash) *MockDigestMethod_Hash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDigestMethod_Hash_Call) RunAndReturn(run func() hash.Hash) *MockDigestMethod_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDigestMethod creates a new instance of MockDigestMethod. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDigestMethod(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDigestMethod {
	mock := &MockDigestMethod{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
