// Code generated by mockery. DO NOT EDIT.

package saml

import (
	http "net/http"

	saml "github.com/adalundhe/saml-gin"
	mock "github.com/stretchr/testify/mock"
)

// MockSessionProvider is an autogenerated mock type for the SessionProvider type
type MockSessionProvider struct {
	mock.Mock
}

type MockSessionProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionProvider) EXPECT() *MockSessionProvider_Expecter {
	return &MockSessionProvider_Expecter{mock: &_m.Mock}
}

// GetSession provides a mock function with given fields: w, r, req
func (_m *MockSessionProvider) GetSession(w http.ResponseWriter, r *http.Request, req *saml.IdpAuthnRequest) *saml.Session {
	ret := _m.Called(w, r, req)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *saml.Session
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, *saml.IdpAuthnRequest) *saml.Session); ok {
		r0 = rf(w, r, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*saml.Session)
		}
	}

	return r0
}

// MockSessionProvider_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockSessionProvider_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - req *saml.IdpAuthnRequest
func (_e *MockSessionProvider_Expecter) GetSession(w interface{}, r interface{}, req interface{}) *MockSessionProvider_GetSession_Call {
	return &MockSessionProvider_GetSession_Call{Call: _e.mock.On("GetSession", w, r, req)}
}

func (_c *MockSessionProvider_GetSession_Call) Run(run func(w http.ResponseWriter, r *http.Request, req *saml.IdpAuthnRequest)) *MockSessionProvider_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request), args[2].(*saml.IdpAuthnRequest))
	})
	return _c
}

func (_c *MockSessionProvider_GetSession_Call) Return(_a0 *saml.Session) *MockSessionProvider_GetSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionProvider_GetSession_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request, *saml.IdpAuthnRequest) *saml.Session) *MockSessionProvider_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionProvider creates a new instance of MockSessionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionProvider {
	mock := &MockSessionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
