// Code generated by mockery. DO NOT EDIT.

package saml

import (
	saml "github.com/adalundhe/saml-gin"
	mock "github.com/stretchr/testify/mock"
)

// MockAssertionMaker is an autogenerated mock type for the AssertionMaker type
type MockAssertionMaker struct {
	mock.Mock
}

type MockAssertionMaker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAssertionMaker) EXPECT() *MockAssertionMaker_Expecter {
	return &MockAssertionMaker_Expecter{mock: &_m.Mock}
}

// MakeAssertion provides a mock function with given fields: req, session
func (_m *MockAssertionMaker) MakeAssertion(req *saml.IdpAuthnRequest, session *saml.Session) error {
	ret := _m.Called(req, session)

	if len(ret) == 0 {
		panic("no return value specified for MakeAssertion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*saml.IdpAuthnRequest, *saml.Session) error); ok {
		r0 = rf(req, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAssertionMaker_MakeAssertion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeAssertion'
type MockAssertionMaker_MakeAssertion_Call struct {
	*mock.Call
}

// MakeAssertion is a helper method to define mock.On call
//   - req *saml.IdpAuthnRequest
//   - session *saml.Session
func (_e *MockAssertionMaker_Expecter) MakeAssertion(req interface{}, session interface{}) *MockAssertionMaker_MakeAssertion_Call {
	return &MockAssertionMaker_MakeAssertion_Call{Call: _e.mock.On("MakeAssertion", req, session)}
}

func (_c *MockAssertionMaker_MakeAssertion_Call) Run(run func(req *saml.IdpAuthnRequest, session *saml.Session)) *MockAssertionMaker_MakeAssertion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*saml.IdpAuthnRequest), args[1].(*saml.Session))
	})
	return _c
}

func (_c *MockAssertionMaker_MakeAssertion_Call) Return(_a0 error) *MockAssertionMaker_MakeAssertion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAssertionMaker_MakeAssertion_Call) RunAndReturn(run func(*saml.IdpAuthnRequest, *saml.Session) error) *MockAssertionMaker_MakeAssertion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAssertionMaker creates a new instance of MockAssertionMaker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssertionMaker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssertionMaker {
	mock := &MockAssertionMaker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
