// Code generated by mockery. DO NOT EDIT.

package saml

import (
	crypto "crypto"
	http "net/http"

	etree "github.com/beevik/etree"

	mock "github.com/stretchr/testify/mock"

	saml "github.com/adalundhe/saml-gin"

	time "time"

	url "net/url"

	x509 "crypto/x509"
)

// MockServiceProvider is an autogenerated mock type for the ServiceProvider type
type MockServiceProvider struct {
	mock.Mock
}

type MockServiceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceProvider) EXPECT() *MockServiceProvider_Expecter {
	return &MockServiceProvider_Expecter{mock: &_m.Mock}
}

// DecryptElement provides a mock function with given fields: encryptedEl
func (_m *MockServiceProvider) DecryptElement(encryptedEl *etree.Element) (*etree.Element, error) {
	ret := _m.Called(encryptedEl)

	if len(ret) == 0 {
		panic("no return value specified for DecryptElement")
	}

	var r0 *etree.Element
	var r1 error
	if rf, ok := ret.Get(0).(func(*etree.Element) (*etree.Element, error)); ok {
		return rf(encryptedEl)
	}
	if rf, ok := ret.Get(0).(func(*etree.Element) *etree.Element); ok {
		r0 = rf(encryptedEl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*etree.Element)
		}
	}

	if rf, ok := ret.Get(1).(func(*etree.Element) error); ok {
		r1 = rf(encryptedEl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceProvider_DecryptElement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptElement'
type MockServiceProvider_DecryptElement_Call struct {
	*mock.Call
}

// DecryptElement is a helper method to define mock.On call
//   - encryptedEl *etree.Element
func (_e *MockServiceProvider_Expecter) DecryptElement(encryptedEl interface{}) *MockServiceProvider_DecryptElement_Call {
	return &MockServiceProvider_DecryptElement_Call{Call: _e.mock.On("DecryptElement", encryptedEl)}
}

func (_c *MockServiceProvider_DecryptElement_Call) Run(run func(encryptedEl *etree.Element)) *MockServiceProvider_DecryptElement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*etree.Element))
	})
	return _c
}

func (_c *MockServiceProvider_DecryptElement_Call) Return(_a0 *etree.Element, _a1 error) *MockServiceProvider_DecryptElement_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceProvider_DecryptElement_Call) RunAndReturn(run func(*etree.Element) (*etree.Element, error)) *MockServiceProvider_DecryptElement_Call {
	_c.Call.Return(run)
	return _c
}

// GetAcsUrl provides a mock function with no fields
func (_m *MockServiceProvider) GetAcsUrl() *url.URL {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAcsUrl")
	}

	var r0 *url.URL
	if rf, ok := ret.Get(0).(func() *url.URL); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}

	return r0
}

// MockServiceProvider_GetAcsUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAcsUrl'
type MockServiceProvider_GetAcsUrl_Call struct {
	*mock.Call
}

// GetAcsUrl is a helper method to define mock.On call
func (_e *MockServiceProvider_Expecter) GetAcsUrl() *MockServiceProvider_GetAcsUrl_Call {
	return &MockServiceProvider_GetAcsUrl_Call{Call: _e.mock.On("GetAcsUrl")}
}

func (_c *MockServiceProvider_GetAcsUrl_Call) Run(run func()) *MockServiceProvider_GetAcsUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceProvider_GetAcsUrl_Call) Return(_a0 *url.URL) *MockServiceProvider_GetAcsUrl_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_GetAcsUrl_Call) RunAndReturn(run func() *url.URL) *MockServiceProvider_GetAcsUrl_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtifactBindingLocation provides a mock function with given fields: binding
func (_m *MockServiceProvider) GetArtifactBindingLocation(binding string) string {
	ret := _m.Called(binding)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifactBindingLocation")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(binding)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockServiceProvider_GetArtifactBindingLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtifactBindingLocation'
type MockServiceProvider_GetArtifactBindingLocation_Call struct {
	*mock.Call
}

// GetArtifactBindingLocation is a helper method to define mock.On call
//   - binding string
func (_e *MockServiceProvider_Expecter) GetArtifactBindingLocation(binding interface{}) *MockServiceProvider_GetArtifactBindingLocation_Call {
	return &MockServiceProvider_GetArtifactBindingLocation_Call{Call: _e.mock.On("GetArtifactBindingLocation", binding)}
}

func (_c *MockServiceProvider_GetArtifactBindingLocation_Call) Run(run func(binding string)) *MockServiceProvider_GetArtifactBindingLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockServiceProvider_GetArtifactBindingLocation_Call) Return(_a0 string) *MockServiceProvider_GetArtifactBindingLocation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_GetArtifactBindingLocation_Call) RunAndReturn(run func(string) string) *MockServiceProvider_GetArtifactBindingLocation_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificate provides a mock function with no fields
func (_m *MockServiceProvider) GetCertificate() *x509.Certificate {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCertificate")
	}

	var r0 *x509.Certificate
	if rf, ok := ret.Get(0).(func() *x509.Certificate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*x509.Certificate)
		}
	}

	return r0
}

// MockServiceProvider_GetCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificate'
type MockServiceProvider_GetCertificate_Call struct {
	*mock.Call
}

// GetCertificate is a helper method to define mock.On call
func (_e *MockServiceProvider_Expecter) GetCertificate() *MockServiceProvider_GetCertificate_Call {
	return &MockServiceProvider_GetCertificate_Call{Call: _e.mock.On("GetCertificate")}
}

func (_c *MockServiceProvider_GetCertificate_Call) Run(run func()) *MockServiceProvider_GetCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceProvider_GetCertificate_Call) Return(_a0 *x509.Certificate) *MockServiceProvider_GetCertificate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_GetCertificate_Call) RunAndReturn(run func() *x509.Certificate) *MockServiceProvider_GetCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefaultRedirectURI provides a mock function with no fields
func (_m *MockServiceProvider) GetDefaultRedirectURI() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultRedirectURI")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockServiceProvider_GetDefaultRedirectURI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultRedirectURI'
type MockServiceProvider_GetDefaultRedirectURI_Call struct {
	*mock.Call
}

// GetDefaultRedirectURI is a helper method to define mock.On call
func (_e *MockServiceProvider_Expecter) GetDefaultRedirectURI() *MockServiceProvider_GetDefaultRedirectURI_Call {
	return &MockServiceProvider_GetDefaultRedirectURI_Call{Call: _e.mock.On("GetDefaultRedirectURI")}
}

func (_c *MockServiceProvider_GetDefaultRedirectURI_Call) Run(run func()) *MockServiceProvider_GetDefaultRedirectURI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceProvider_GetDefaultRedirectURI_Call) Return(_a0 string) *MockServiceProvider_GetDefaultRedirectURI_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_GetDefaultRedirectURI_Call) RunAndReturn(run func() string) *MockServiceProvider_GetDefaultRedirectURI_Call {
	_c.Call.Return(run)
	return _c
}

// GetIDPMetadata provides a mock function with no fields
func (_m *MockServiceProvider) GetIDPMetadata() *saml.EntityDescriptor {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetIDPMetadata")
	}

	var r0 *saml.EntityDescriptor
	if rf, ok := ret.Get(0).(func() *saml.EntityDescriptor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*saml.EntityDescriptor)
		}
	}

	return r0
}

// MockServiceProvider_GetIDPMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIDPMetadata'
type MockServiceProvider_GetIDPMetadata_Call struct {
	*mock.Call
}

// GetIDPMetadata is a helper method to define mock.On call
func (_e *MockServiceProvider_Expecter) GetIDPMetadata() *MockServiceProvider_GetIDPMetadata_Call {
	return &MockServiceProvider_GetIDPMetadata_Call{Call: _e.mock.On("GetIDPMetadata")}
}

func (_c *MockServiceProvider_GetIDPMetadata_Call) Run(run func()) *MockServiceProvider_GetIDPMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceProvider_GetIDPMetadata_Call) Return(_a0 *saml.EntityDescriptor) *MockServiceProvider_GetIDPMetadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_GetIDPMetadata_Call) RunAndReturn(run func() *saml.EntityDescriptor) *MockServiceProvider_GetIDPMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetKey provides a mock function with no fields
func (_m *MockServiceProvider) GetKey() crypto.Signer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetKey")
	}

	var r0 crypto.Signer
	if rf, ok := ret.Get(0).(func() crypto.Signer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.Signer)
		}
	}

	return r0
}

// MockServiceProvider_GetKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKey'
type MockServiceProvider_GetKey_Call struct {
	*mock.Call
}

// GetKey is a helper method to define mock.On call
func (_e *MockServiceProvider_Expecter) GetKey() *MockServiceProvider_GetKey_Call {
	return &MockServiceProvider_GetKey_Call{Call: _e.mock.On("GetKey")}
}

func (_c *MockServiceProvider_GetKey_Call) Run(run func()) *MockServiceProvider_GetKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceProvider_GetKey_Call) Return(_a0 crypto.Signer) *MockServiceProvider_GetKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_GetKey_Call) RunAndReturn(run func() crypto.Signer) *MockServiceProvider_GetKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetadataURL provides a mock function with no fields
func (_m *MockServiceProvider) GetMetadataURL() url.URL {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetadataURL")
	}

	var r0 url.URL
	if rf, ok := ret.Get(0).(func() url.URL); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(url.URL)
	}

	return r0
}

// MockServiceProvider_GetMetadataURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetadataURL'
type MockServiceProvider_GetMetadataURL_Call struct {
	*mock.Call
}

// GetMetadataURL is a helper method to define mock.On call
func (_e *MockServiceProvider_Expecter) GetMetadataURL() *MockServiceProvider_GetMetadataURL_Call {
	return &MockServiceProvider_GetMetadataURL_Call{Call: _e.mock.On("GetMetadataURL")}
}

func (_c *MockServiceProvider_GetMetadataURL_Call) Run(run func()) *MockServiceProvider_GetMetadataURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceProvider_GetMetadataURL_Call) Return(_a0 url.URL) *MockServiceProvider_GetMetadataURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_GetMetadataURL_Call) RunAndReturn(run func() url.URL) *MockServiceProvider_GetMetadataURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetSLOBindingLocation provides a mock function with given fields: binding
func (_m *MockServiceProvider) GetSLOBindingLocation(binding string) string {
	ret := _m.Called(binding)

	if len(ret) == 0 {
		panic("no return value specified for GetSLOBindingLocation")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(binding)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockServiceProvider_GetSLOBindingLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSLOBindingLocation'
type MockServiceProvider_GetSLOBindingLocation_Call struct {
	*mock.Call
}

// GetSLOBindingLocation is a helper method to define mock.On call
//   - binding string
func (_e *MockServiceProvider_Expecter) GetSLOBindingLocation(binding interface{}) *MockServiceProvider_GetSLOBindingLocation_Call {
	return &MockServiceProvider_GetSLOBindingLocation_Call{Call: _e.mock.On("GetSLOBindingLocation", binding)}
}

func (_c *MockServiceProvider_GetSLOBindingLocation_Call) Run(run func(binding string)) *MockServiceProvider_GetSLOBindingLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockServiceProvider_GetSLOBindingLocation_Call) Return(_a0 string) *MockServiceProvider_GetSLOBindingLocation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_GetSLOBindingLocation_Call) RunAndReturn(run func(string) string) *MockServiceProvider_GetSLOBindingLocation_Call {
	_c.Call.Return(run)
	return _c
}

// GetSSOBindingLocation provides a mock function with given fields: binding
func (_m *MockServiceProvider) GetSSOBindingLocation(binding string) string {
	ret := _m.Called(binding)

	if len(ret) == 0 {
		panic("no return value specified for GetSSOBindingLocation")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(binding)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockServiceProvider_GetSSOBindingLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSSOBindingLocation'
type MockServiceProvider_GetSSOBindingLocation_Call struct {
	*mock.Call
}

// GetSSOBindingLocation is a helper method to define mock.On call
//   - binding string
func (_e *MockServiceProvider_Expecter) GetSSOBindingLocation(binding interface{}) *MockServiceProvider_GetSSOBindingLocation_Call {
	return &MockServiceProvider_GetSSOBindingLocation_Call{Call: _e.mock.On("GetSSOBindingLocation", binding)}
}

func (_c *MockServiceProvider_GetSSOBindingLocation_Call) Run(run func(binding string)) *MockServiceProvider_GetSSOBindingLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockServiceProvider_GetSSOBindingLocation_Call) Return(_a0 string) *MockServiceProvider_GetSSOBindingLocation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_GetSSOBindingLocation_Call) RunAndReturn(run func(string) string) *MockServiceProvider_GetSSOBindingLocation_Call {
	_c.Call.Return(run)
	return _c
}

// GetSignatureMethod provides a mock function with no fields
func (_m *MockServiceProvider) GetSignatureMethod() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSignatureMethod")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockServiceProvider_GetSignatureMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSignatureMethod'
type MockServiceProvider_GetSignatureMethod_Call struct {
	*mock.Call
}

// GetSignatureMethod is a helper method to define mock.On call
func (_e *MockServiceProvider_Expecter) GetSignatureMethod() *MockServiceProvider_GetSignatureMethod_Call {
	return &MockServiceProvider_GetSignatureMethod_Call{Call: _e.mock.On("GetSignatureMethod")}
}

func (_c *MockServiceProvider_GetSignatureMethod_Call) Run(run func()) *MockServiceProvider_GetSignatureMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceProvider_GetSignatureMethod_Call) Return(_a0 string) *MockServiceProvider_GetSignatureMethod_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_GetSignatureMethod_Call) RunAndReturn(run func() string) *MockServiceProvider_GetSignatureMethod_Call {
	_c.Call.Return(run)
	return _c
}

// GetSloUrl provides a mock function with no fields
func (_m *MockServiceProvider) GetSloUrl() url.URL {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSloUrl")
	}

	var r0 url.URL
	if rf, ok := ret.Get(0).(func() url.URL); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(url.URL)
	}

	return r0
}

// MockServiceProvider_GetSloUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSloUrl'
type MockServiceProvider_GetSloUrl_Call struct {
	*mock.Call
}

// GetSloUrl is a helper method to define mock.On call
func (_e *MockServiceProvider_Expecter) GetSloUrl() *MockServiceProvider_GetSloUrl_Call {
	return &MockServiceProvider_GetSloUrl_Call{Call: _e.mock.On("GetSloUrl")}
}

func (_c *MockServiceProvider_GetSloUrl_Call) Run(run func()) *MockServiceProvider_GetSloUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceProvider_GetSloUrl_Call) Return(_a0 url.URL) *MockServiceProvider_GetSloUrl_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_GetSloUrl_Call) RunAndReturn(run func() url.URL) *MockServiceProvider_GetSloUrl_Call {
	_c.Call.Return(run)
	return _c
}

// IDPInitiatedAllowed provides a mock function with no fields
func (_m *MockServiceProvider) IDPInitiatedAllowed() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IDPInitiatedAllowed")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockServiceProvider_IDPInitiatedAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IDPInitiatedAllowed'
type MockServiceProvider_IDPInitiatedAllowed_Call struct {
	*mock.Call
}

// IDPInitiatedAllowed is a helper method to define mock.On call
func (_e *MockServiceProvider_Expecter) IDPInitiatedAllowed() *MockServiceProvider_IDPInitiatedAllowed_Call {
	return &MockServiceProvider_IDPInitiatedAllowed_Call{Call: _e.mock.On("IDPInitiatedAllowed")}
}

func (_c *MockServiceProvider_IDPInitiatedAllowed_Call) Run(run func()) *MockServiceProvider_IDPInitiatedAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceProvider_IDPInitiatedAllowed_Call) Return(_a0 bool) *MockServiceProvider_IDPInitiatedAllowed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_IDPInitiatedAllowed_Call) RunAndReturn(run func() bool) *MockServiceProvider_IDPInitiatedAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// MakeArtifactResolveRequest provides a mock function with given fields: artifactID
func (_m *MockServiceProvider) MakeArtifactResolveRequest(artifactID string) (*saml.ArtifactResolve, error) {
	ret := _m.Called(artifactID)

	if len(ret) == 0 {
		panic("no return value specified for MakeArtifactResolveRequest")
	}

	var r0 *saml.ArtifactResolve
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*saml.ArtifactResolve, error)); ok {
		return rf(artifactID)
	}
	if rf, ok := ret.Get(0).(func(string) *saml.ArtifactResolve); ok {
		r0 = rf(artifactID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*saml.ArtifactResolve)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(artifactID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceProvider_MakeArtifactResolveRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeArtifactResolveRequest'
type MockServiceProvider_MakeArtifactResolveRequest_Call struct {
	*mock.Call
}

// MakeArtifactResolveRequest is a helper method to define mock.On call
//   - artifactID string
func (_e *MockServiceProvider_Expecter) MakeArtifactResolveRequest(artifactID interface{}) *MockServiceProvider_MakeArtifactResolveRequest_Call {
	return &MockServiceProvider_MakeArtifactResolveRequest_Call{Call: _e.mock.On("MakeArtifactResolveRequest", artifactID)}
}

func (_c *MockServiceProvider_MakeArtifactResolveRequest_Call) Run(run func(artifactID string)) *MockServiceProvider_MakeArtifactResolveRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockServiceProvider_MakeArtifactResolveRequest_Call) Return(_a0 *saml.ArtifactResolve, _a1 error) *MockServiceProvider_MakeArtifactResolveRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceProvider_MakeArtifactResolveRequest_Call) RunAndReturn(run func(string) (*saml.ArtifactResolve, error)) *MockServiceProvider_MakeArtifactResolveRequest_Call {
	_c.Call.Return(run)
	return _c
}

// MakeAuthenticationRequest provides a mock function with given fields: idpURL, binding, resultBinding
func (_m *MockServiceProvider) MakeAuthenticationRequest(idpURL string, binding string, resultBinding string) (*saml.AuthnRequest, error) {
	ret := _m.Called(idpURL, binding, resultBinding)

	if len(ret) == 0 {
		panic("no return value specified for MakeAuthenticationRequest")
	}

	var r0 *saml.AuthnRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*saml.AuthnRequest, error)); ok {
		return rf(idpURL, binding, resultBinding)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *saml.AuthnRequest); ok {
		r0 = rf(idpURL, binding, resultBinding)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*saml.AuthnRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(idpURL, binding, resultBinding)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceProvider_MakeAuthenticationRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeAuthenticationRequest'
type MockServiceProvider_MakeAuthenticationRequest_Call struct {
	*mock.Call
}

// MakeAuthenticationRequest is a helper method to define mock.On call
//   - idpURL string
//   - binding string
//   - resultBinding string
func (_e *MockServiceProvider_Expecter) MakeAuthenticationRequest(idpURL interface{}, binding interface{}, resultBinding interface{}) *MockServiceProvider_MakeAuthenticationRequest_Call {
	return &MockServiceProvider_MakeAuthenticationRequest_Call{Call: _e.mock.On("MakeAuthenticationRequest", idpURL, binding, resultBinding)}
}

func (_c *MockServiceProvider_MakeAuthenticationRequest_Call) Run(run func(idpURL string, binding string, resultBinding string)) *MockServiceProvider_MakeAuthenticationRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockServiceProvider_MakeAuthenticationRequest_Call) Return(_a0 *saml.AuthnRequest, _a1 error) *MockServiceProvider_MakeAuthenticationRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceProvider_MakeAuthenticationRequest_Call) RunAndReturn(run func(string, string, string) (*saml.AuthnRequest, error)) *MockServiceProvider_MakeAuthenticationRequest_Call {
	_c.Call.Return(run)
	return _c
}

// MakeLogoutRequest provides a mock function with given fields: idpURL, nameID
func (_m *MockServiceProvider) MakeLogoutRequest(idpURL string, nameID string) (*saml.LogoutRequest, error) {
	ret := _m.Called(idpURL, nameID)

	if len(ret) == 0 {
		panic("no return value specified for MakeLogoutRequest")
	}

	var r0 *saml.LogoutRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*saml.LogoutRequest, error)); ok {
		return rf(idpURL, nameID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *saml.LogoutRequest); ok {
		r0 = rf(idpURL, nameID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*saml.LogoutRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(idpURL, nameID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceProvider_MakeLogoutRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeLogoutRequest'
type MockServiceProvider_MakeLogoutRequest_Call struct {
	*mock.Call
}

// MakeLogoutRequest is a helper method to define mock.On call
//   - idpURL string
//   - nameID string
func (_e *MockServiceProvider_Expecter) MakeLogoutRequest(idpURL interface{}, nameID interface{}) *MockServiceProvider_MakeLogoutRequest_Call {
	return &MockServiceProvider_MakeLogoutRequest_Call{Call: _e.mock.On("MakeLogoutRequest", idpURL, nameID)}
}

func (_c *MockServiceProvider_MakeLogoutRequest_Call) Run(run func(idpURL string, nameID string)) *MockServiceProvider_MakeLogoutRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockServiceProvider_MakeLogoutRequest_Call) Return(_a0 *saml.LogoutRequest, _a1 error) *MockServiceProvider_MakeLogoutRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceProvider_MakeLogoutRequest_Call) RunAndReturn(run func(string, string) (*saml.LogoutRequest, error)) *MockServiceProvider_MakeLogoutRequest_Call {
	_c.Call.Return(run)
	return _c
}

// MakeLogoutResponse provides a mock function with given fields: idpURL, logoutRequestID
func (_m *MockServiceProvider) MakeLogoutResponse(idpURL string, logoutRequestID string) (*saml.LogoutResponse, error) {
	ret := _m.Called(idpURL, logoutRequestID)

	if len(ret) == 0 {
		panic("no return value specified for MakeLogoutResponse")
	}

	var r0 *saml.LogoutResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*saml.LogoutResponse, error)); ok {
		return rf(idpURL, logoutRequestID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *saml.LogoutResponse); ok {
		r0 = rf(idpURL, logoutRequestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*saml.LogoutResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(idpURL, logoutRequestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceProvider_MakeLogoutResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeLogoutResponse'
type MockServiceProvider_MakeLogoutResponse_Call struct {
	*mock.Call
}

// MakeLogoutResponse is a helper method to define mock.On call
//   - idpURL string
//   - logoutRequestID string
func (_e *MockServiceProvider_Expecter) MakeLogoutResponse(idpURL interface{}, logoutRequestID interface{}) *MockServiceProvider_MakeLogoutResponse_Call {
	return &MockServiceProvider_MakeLogoutResponse_Call{Call: _e.mock.On("MakeLogoutResponse", idpURL, logoutRequestID)}
}

func (_c *MockServiceProvider_MakeLogoutResponse_Call) Run(run func(idpURL string, logoutRequestID string)) *MockServiceProvider_MakeLogoutResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockServiceProvider_MakeLogoutResponse_Call) Return(_a0 *saml.LogoutResponse, _a1 error) *MockServiceProvider_MakeLogoutResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceProvider_MakeLogoutResponse_Call) RunAndReturn(run func(string, string) (*saml.LogoutResponse, error)) *MockServiceProvider_MakeLogoutResponse_Call {
	_c.Call.Return(run)
	return _c
}

// MakePostAuthenticationRequest provides a mock function with given fields: relayState
func (_m *MockServiceProvider) MakePostAuthenticationRequest(relayState string) ([]byte, error) {
	ret := _m.Called(relayState)

	if len(ret) == 0 {
		panic("no return value specified for MakePostAuthenticationRequest")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(relayState)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(relayState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(relayState)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceProvider_MakePostAuthenticationRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakePostAuthenticationRequest'
type MockServiceProvider_MakePostAuthenticationRequest_Call struct {
	*mock.Call
}

// MakePostAuthenticationRequest is a helper method to define mock.On call
//   - relayState string
func (_e *MockServiceProvider_Expecter) MakePostAuthenticationRequest(relayState interface{}) *MockServiceProvider_MakePostAuthenticationRequest_Call {
	return &MockServiceProvider_MakePostAuthenticationRequest_Call{Call: _e.mock.On("MakePostAuthenticationRequest", relayState)}
}

func (_c *MockServiceProvider_MakePostAuthenticationRequest_Call) Run(run func(relayState string)) *MockServiceProvider_MakePostAuthenticationRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockServiceProvider_MakePostAuthenticationRequest_Call) Return(_a0 []byte, _a1 error) *MockServiceProvider_MakePostAuthenticationRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceProvider_MakePostAuthenticationRequest_Call) RunAndReturn(run func(string) ([]byte, error)) *MockServiceProvider_MakePostAuthenticationRequest_Call {
	_c.Call.Return(run)
	return _c
}

// MakePostLogoutRequest provides a mock function with given fields: nameID, relayState
func (_m *MockServiceProvider) MakePostLogoutRequest(nameID string, relayState string) ([]byte, error) {
	ret := _m.Called(nameID, relayState)

	if len(ret) == 0 {
		panic("no return value specified for MakePostLogoutRequest")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]byte, error)); ok {
		return rf(nameID, relayState)
	}
	if rf, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = rf(nameID, relayState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(nameID, relayState)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceProvider_MakePostLogoutRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakePostLogoutRequest'
type MockServiceProvider_MakePostLogoutRequest_Call struct {
	*mock.Call
}

// MakePostLogoutRequest is a helper method to define mock.On call
//   - nameID string
//   - relayState string
func (_e *MockServiceProvider_Expecter) MakePostLogoutRequest(nameID interface{}, relayState interface{}) *MockServiceProvider_MakePostLogoutRequest_Call {
	return &MockServiceProvider_MakePostLogoutRequest_Call{Call: _e.mock.On("MakePostLogoutRequest", nameID, relayState)}
}

func (_c *MockServiceProvider_MakePostLogoutRequest_Call) Run(run func(nameID string, relayState string)) *MockServiceProvider_MakePostLogoutRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockServiceProvider_MakePostLogoutRequest_Call) Return(_a0 []byte, _a1 error) *MockServiceProvider_MakePostLogoutRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceProvider_MakePostLogoutRequest_Call) RunAndReturn(run func(string, string) ([]byte, error)) *MockServiceProvider_MakePostLogoutRequest_Call {
	_c.Call.Return(run)
	return _c
}

// MakePostLogoutResponse provides a mock function with given fields: logoutRequestID, relayState
func (_m *MockServiceProvider) MakePostLogoutResponse(logoutRequestID string, relayState string) ([]byte, error) {
	ret := _m.Called(logoutRequestID, relayState)

	if len(ret) == 0 {
		panic("no return value specified for MakePostLogoutResponse")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]byte, error)); ok {
		return rf(logoutRequestID, relayState)
	}
	if rf, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = rf(logoutRequestID, relayState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(logoutRequestID, relayState)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceProvider_MakePostLogoutResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakePostLogoutResponse'
type MockServiceProvider_MakePostLogoutResponse_Call struct {
	*mock.Call
}

// MakePostLogoutResponse is a helper method to define mock.On call
//   - logoutRequestID string
//   - relayState string
func (_e *MockServiceProvider_Expecter) MakePostLogoutResponse(logoutRequestID interface{}, relayState interface{}) *MockServiceProvider_MakePostLogoutResponse_Call {
	return &MockServiceProvider_MakePostLogoutResponse_Call{Call: _e.mock.On("MakePostLogoutResponse", logoutRequestID, relayState)}
}

func (_c *MockServiceProvider_MakePostLogoutResponse_Call) Run(run func(logoutRequestID string, relayState string)) *MockServiceProvider_MakePostLogoutResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockServiceProvider_MakePostLogoutResponse_Call) Return(_a0 []byte, _a1 error) *MockServiceProvider_MakePostLogoutResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceProvider_MakePostLogoutResponse_Call) RunAndReturn(run func(string, string) ([]byte, error)) *MockServiceProvider_MakePostLogoutResponse_Call {
	_c.Call.Return(run)
	return _c
}

// MakeRedirectAuthenticationRequest provides a mock function with given fields: relayState
func (_m *MockServiceProvider) MakeRedirectAuthenticationRequest(relayState string) (*url.URL, error) {
	ret := _m.Called(relayState)

	if len(ret) == 0 {
		panic("no return value specified for MakeRedirectAuthenticationRequest")
	}

	var r0 *url.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*url.URL, error)); ok {
		return rf(relayState)
	}
	if rf, ok := ret.Get(0).(func(string) *url.URL); ok {
		r0 = rf(relayState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(relayState)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceProvider_MakeRedirectAuthenticationRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeRedirectAuthenticationRequest'
type MockServiceProvider_MakeRedirectAuthenticationRequest_Call struct {
	*mock.Call
}

// MakeRedirectAuthenticationRequest is a helper method to define mock.On call
//   - relayState string
func (_e *MockServiceProvider_Expecter) MakeRedirectAuthenticationRequest(relayState interface{}) *MockServiceProvider_MakeRedirectAuthenticationRequest_Call {
	return &MockServiceProvider_MakeRedirectAuthenticationRequest_Call{Call: _e.mock.On("MakeRedirectAuthenticationRequest", relayState)}
}

func (_c *MockServiceProvider_MakeRedirectAuthenticationRequest_Call) Run(run func(relayState string)) *MockServiceProvider_MakeRedirectAuthenticationRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockServiceProvider_MakeRedirectAuthenticationRequest_Call) Return(_a0 *url.URL, _a1 error) *MockServiceProvider_MakeRedirectAuthenticationRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceProvider_MakeRedirectAuthenticationRequest_Call) RunAndReturn(run func(string) (*url.URL, error)) *MockServiceProvider_MakeRedirectAuthenticationRequest_Call {
	_c.Call.Return(run)
	return _c
}

// MakeRedirectLogoutRequest provides a mock function with given fields: nameID, relayState
func (_m *MockServiceProvider) MakeRedirectLogoutRequest(nameID string, relayState string) (*url.URL, error) {
	ret := _m.Called(nameID, relayState)

	if len(ret) == 0 {
		panic("no return value specified for MakeRedirectLogoutRequest")
	}

	var r0 *url.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*url.URL, error)); ok {
		return rf(nameID, relayState)
	}
	if rf, ok := ret.Get(0).(func(string, string) *url.URL); ok {
		r0 = rf(nameID, relayState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(nameID, relayState)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceProvider_MakeRedirectLogoutRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeRedirectLogoutRequest'
type MockServiceProvider_MakeRedirectLogoutRequest_Call struct {
	*mock.Call
}

// MakeRedirectLogoutRequest is a helper method to define mock.On call
//   - nameID string
//   - relayState string
func (_e *MockServiceProvider_Expecter) MakeRedirectLogoutRequest(nameID interface{}, relayState interface{}) *MockServiceProvider_MakeRedirectLogoutRequest_Call {
	return &MockServiceProvider_MakeRedirectLogoutRequest_Call{Call: _e.mock.On("MakeRedirectLogoutRequest", nameID, relayState)}
}

func (_c *MockServiceProvider_MakeRedirectLogoutRequest_Call) Run(run func(nameID string, relayState string)) *MockServiceProvider_MakeRedirectLogoutRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockServiceProvider_MakeRedirectLogoutRequest_Call) Return(_a0 *url.URL, _a1 error) *MockServiceProvider_MakeRedirectLogoutRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceProvider_MakeRedirectLogoutRequest_Call) RunAndReturn(run func(string, string) (*url.URL, error)) *MockServiceProvider_MakeRedirectLogoutRequest_Call {
	_c.Call.Return(run)
	return _c
}

// MakeRedirectLogoutResponse provides a mock function with given fields: logoutRequestID, relayState
func (_m *MockServiceProvider) MakeRedirectLogoutResponse(logoutRequestID string, relayState string) (*url.URL, error) {
	ret := _m.Called(logoutRequestID, relayState)

	if len(ret) == 0 {
		panic("no return value specified for MakeRedirectLogoutResponse")
	}

	var r0 *url.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*url.URL, error)); ok {
		return rf(logoutRequestID, relayState)
	}
	if rf, ok := ret.Get(0).(func(string, string) *url.URL); ok {
		r0 = rf(logoutRequestID, relayState)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(logoutRequestID, relayState)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceProvider_MakeRedirectLogoutResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeRedirectLogoutResponse'
type MockServiceProvider_MakeRedirectLogoutResponse_Call struct {
	*mock.Call
}

// MakeRedirectLogoutResponse is a helper method to define mock.On call
//   - logoutRequestID string
//   - relayState string
func (_e *MockServiceProvider_Expecter) MakeRedirectLogoutResponse(logoutRequestID interface{}, relayState interface{}) *MockServiceProvider_MakeRedirectLogoutResponse_Call {
	return &MockServiceProvider_MakeRedirectLogoutResponse_Call{Call: _e.mock.On("MakeRedirectLogoutResponse", logoutRequestID, relayState)}
}

func (_c *MockServiceProvider_MakeRedirectLogoutResponse_Call) Run(run func(logoutRequestID string, relayState string)) *MockServiceProvider_MakeRedirectLogoutResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockServiceProvider_MakeRedirectLogoutResponse_Call) Return(_a0 *url.URL, _a1 error) *MockServiceProvider_MakeRedirectLogoutResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceProvider_MakeRedirectLogoutResponse_Call) RunAndReturn(run func(string, string) (*url.URL, error)) *MockServiceProvider_MakeRedirectLogoutResponse_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function with no fields
func (_m *MockServiceProvider) Metadata() *saml.EntityDescriptor {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 *saml.EntityDescriptor
	if rf, ok := ret.Get(0).(func() *saml.EntityDescriptor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*saml.EntityDescriptor)
		}
	}

	return r0
}

// MockServiceProvider_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockServiceProvider_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockServiceProvider_Expecter) Metadata() *MockServiceProvider_Metadata_Call {
	return &MockServiceProvider_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockServiceProvider_Metadata_Call) Run(run func()) *MockServiceProvider_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceProvider_Metadata_Call) Return(_a0 *saml.EntityDescriptor) *MockServiceProvider_Metadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_Metadata_Call) RunAndReturn(run func() *saml.EntityDescriptor) *MockServiceProvider_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// ParseResponse provides a mock function with given fields: req, possibleRequestIDs
func (_m *MockServiceProvider) ParseResponse(req *http.Request, possibleRequestIDs []string) (*saml.Assertion, error) {
	ret := _m.Called(req, possibleRequestIDs)

	if len(ret) == 0 {
		panic("no return value specified for ParseResponse")
	}

	var r0 *saml.Assertion
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request, []string) (*saml.Assertion, error)); ok {
		return rf(req, possibleRequestIDs)
	}
	if rf, ok := ret.Get(0).(func(*http.Request, []string) *saml.Assertion); ok {
		r0 = rf(req, possibleRequestIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*saml.Assertion)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request, []string) error); ok {
		r1 = rf(req, possibleRequestIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceProvider_ParseResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseResponse'
type MockServiceProvider_ParseResponse_Call struct {
	*mock.Call
}

// ParseResponse is a helper method to define mock.On call
//   - req *http.Request
//   - possibleRequestIDs []string
func (_e *MockServiceProvider_Expecter) ParseResponse(req interface{}, possibleRequestIDs interface{}) *MockServiceProvider_ParseResponse_Call {
	return &MockServiceProvider_ParseResponse_Call{Call: _e.mock.On("ParseResponse", req, possibleRequestIDs)}
}

func (_c *MockServiceProvider_ParseResponse_Call) Run(run func(req *http.Request, possibleRequestIDs []string)) *MockServiceProvider_ParseResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request), args[1].([]string))
	})
	return _c
}

func (_c *MockServiceProvider_ParseResponse_Call) Return(_a0 *saml.Assertion, _a1 error) *MockServiceProvider_ParseResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceProvider_ParseResponse_Call) RunAndReturn(run func(*http.Request, []string) (*saml.Assertion, error)) *MockServiceProvider_ParseResponse_Call {
	_c.Call.Return(run)
	return _c
}

// ParseXMLArtifactResponse provides a mock function with given fields: soapResponseXML, possibleRequestIDs, artifactRequestID, currentURL
func (_m *MockServiceProvider) ParseXMLArtifactResponse(soapResponseXML []byte, possibleRequestIDs []string, artifactRequestID string, currentURL url.URL) (*saml.Assertion, error) {
	ret := _m.Called(soapResponseXML, possibleRequestIDs, artifactRequestID, currentURL)

	if len(ret) == 0 {
		panic("no return value specified for ParseXMLArtifactResponse")
	}

	var r0 *saml.Assertion
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []string, string, url.URL) (*saml.Assertion, error)); ok {
		return rf(soapResponseXML, possibleRequestIDs, artifactRequestID, currentURL)
	}
	if rf, ok := ret.Get(0).(func([]byte, []string, string, url.URL) *saml.Assertion); ok {
		r0 = rf(soapResponseXML, possibleRequestIDs, artifactRequestID, currentURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*saml.Assertion)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []string, string, url.URL) error); ok {
		r1 = rf(soapResponseXML, possibleRequestIDs, artifactRequestID, currentURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceProvider_ParseXMLArtifactResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseXMLArtifactResponse'
type MockServiceProvider_ParseXMLArtifactResponse_Call struct {
	*mock.Call
}

// ParseXMLArtifactResponse is a helper method to define mock.On call
//   - soapResponseXML []byte
//   - possibleRequestIDs []string
//   - artifactRequestID string
//   - currentURL url.URL
func (_e *MockServiceProvider_Expecter) ParseXMLArtifactResponse(soapResponseXML interface{}, possibleRequestIDs interface{}, artifactRequestID interface{}, currentURL interface{}) *MockServiceProvider_ParseXMLArtifactResponse_Call {
	return &MockServiceProvider_ParseXMLArtifactResponse_Call{Call: _e.mock.On("ParseXMLArtifactResponse", soapResponseXML, possibleRequestIDs, artifactRequestID, currentURL)}
}

func (_c *MockServiceProvider_ParseXMLArtifactResponse_Call) Run(run func(soapResponseXML []byte, possibleRequestIDs []string, artifactRequestID string, currentURL url.URL)) *MockServiceProvider_ParseXMLArtifactResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].([]string), args[2].(string), args[3].(url.URL))
	})
	return _c
}

func (_c *MockServiceProvider_ParseXMLArtifactResponse_Call) Return(_a0 *saml.Assertion, _a1 error) *MockServiceProvider_ParseXMLArtifactResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceProvider_ParseXMLArtifactResponse_Call) RunAndReturn(run func([]byte, []string, string, url.URL) (*saml.Assertion, error)) *MockServiceProvider_ParseXMLArtifactResponse_Call {
	_c.Call.Return(run)
	return _c
}

// ParseXMLResponse provides a mock function with given fields: decodedResponseXML, possibleRequestIDs, currentURL
func (_m *MockServiceProvider) ParseXMLResponse(decodedResponseXML []byte, possibleRequestIDs []string, currentURL url.URL) (*saml.Assertion, error) {
	ret := _m.Called(decodedResponseXML, possibleRequestIDs, currentURL)

	if len(ret) == 0 {
		panic("no return value specified for ParseXMLResponse")
	}

	var r0 *saml.Assertion
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, []string, url.URL) (*saml.Assertion, error)); ok {
		return rf(decodedResponseXML, possibleRequestIDs, currentURL)
	}
	if rf, ok := ret.Get(0).(func([]byte, []string, url.URL) *saml.Assertion); ok {
		r0 = rf(decodedResponseXML, possibleRequestIDs, currentURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*saml.Assertion)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, []string, url.URL) error); ok {
		r1 = rf(decodedResponseXML, possibleRequestIDs, currentURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceProvider_ParseXMLResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseXMLResponse'
type MockServiceProvider_ParseXMLResponse_Call struct {
	*mock.Call
}

// ParseXMLResponse is a helper method to define mock.On call
//   - decodedResponseXML []byte
//   - possibleRequestIDs []string
//   - currentURL url.URL
func (_e *MockServiceProvider_Expecter) ParseXMLResponse(decodedResponseXML interface{}, possibleRequestIDs interface{}, currentURL interface{}) *MockServiceProvider_ParseXMLResponse_Call {
	return &MockServiceProvider_ParseXMLResponse_Call{Call: _e.mock.On("ParseXMLResponse", decodedResponseXML, possibleRequestIDs, currentURL)}
}

func (_c *MockServiceProvider_ParseXMLResponse_Call) Run(run func(decodedResponseXML []byte, possibleRequestIDs []string, currentURL url.URL)) *MockServiceProvider_ParseXMLResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].([]string), args[2].(url.URL))
	})
	return _c
}

func (_c *MockServiceProvider_ParseXMLResponse_Call) Return(_a0 *saml.Assertion, _a1 error) *MockServiceProvider_ParseXMLResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceProvider_ParseXMLResponse_Call) RunAndReturn(run func([]byte, []string, url.URL) (*saml.Assertion, error)) *MockServiceProvider_ParseXMLResponse_Call {
	_c.Call.Return(run)
	return _c
}

// SetAcsUrl provides a mock function with given fields: _a0
func (_m *MockServiceProvider) SetAcsUrl(_a0 url.URL) {
	_m.Called(_a0)
}

// MockServiceProvider_SetAcsUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAcsUrl'
type MockServiceProvider_SetAcsUrl_Call struct {
	*mock.Call
}

// SetAcsUrl is a helper method to define mock.On call
//   - _a0 url.URL
func (_e *MockServiceProvider_Expecter) SetAcsUrl(_a0 interface{}) *MockServiceProvider_SetAcsUrl_Call {
	return &MockServiceProvider_SetAcsUrl_Call{Call: _e.mock.On("SetAcsUrl", _a0)}
}

func (_c *MockServiceProvider_SetAcsUrl_Call) Run(run func(_a0 url.URL)) *MockServiceProvider_SetAcsUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(url.URL))
	})
	return _c
}

func (_c *MockServiceProvider_SetAcsUrl_Call) Return() *MockServiceProvider_SetAcsUrl_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServiceProvider_SetAcsUrl_Call) RunAndReturn(run func(url.URL)) *MockServiceProvider_SetAcsUrl_Call {
	_c.Run(run)
	return _c
}

// SetAuthnNameIDFormat provides a mock function with given fields: format
func (_m *MockServiceProvider) SetAuthnNameIDFormat(format saml.NameIDFormat) {
	_m.Called(format)
}

// MockServiceProvider_SetAuthnNameIDFormat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAuthnNameIDFormat'
type MockServiceProvider_SetAuthnNameIDFormat_Call struct {
	*mock.Call
}

// SetAuthnNameIDFormat is a helper method to define mock.On call
//   - format saml.NameIDFormat
func (_e *MockServiceProvider_Expecter) SetAuthnNameIDFormat(format interface{}) *MockServiceProvider_SetAuthnNameIDFormat_Call {
	return &MockServiceProvider_SetAuthnNameIDFormat_Call{Call: _e.mock.On("SetAuthnNameIDFormat", format)}
}

func (_c *MockServiceProvider_SetAuthnNameIDFormat_Call) Run(run func(format saml.NameIDFormat)) *MockServiceProvider_SetAuthnNameIDFormat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(saml.NameIDFormat))
	})
	return _c
}

func (_c *MockServiceProvider_SetAuthnNameIDFormat_Call) Return() *MockServiceProvider_SetAuthnNameIDFormat_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServiceProvider_SetAuthnNameIDFormat_Call) RunAndReturn(run func(saml.NameIDFormat)) *MockServiceProvider_SetAuthnNameIDFormat_Call {
	_c.Run(run)
	return _c
}

// SetIDPMetadata provides a mock function with given fields: idpMetadata
func (_m *MockServiceProvider) SetIDPMetadata(idpMetadata *saml.EntityDescriptor) {
	_m.Called(idpMetadata)
}

// MockServiceProvider_SetIDPMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIDPMetadata'
type MockServiceProvider_SetIDPMetadata_Call struct {
	*mock.Call
}

// SetIDPMetadata is a helper method to define mock.On call
//   - idpMetadata *saml.EntityDescriptor
func (_e *MockServiceProvider_Expecter) SetIDPMetadata(idpMetadata interface{}) *MockServiceProvider_SetIDPMetadata_Call {
	return &MockServiceProvider_SetIDPMetadata_Call{Call: _e.mock.On("SetIDPMetadata", idpMetadata)}
}

func (_c *MockServiceProvider_SetIDPMetadata_Call) Run(run func(idpMetadata *saml.EntityDescriptor)) *MockServiceProvider_SetIDPMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*saml.EntityDescriptor))
	})
	return _c
}

func (_c *MockServiceProvider_SetIDPMetadata_Call) Return() *MockServiceProvider_SetIDPMetadata_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServiceProvider_SetIDPMetadata_Call) RunAndReturn(run func(*saml.EntityDescriptor)) *MockServiceProvider_SetIDPMetadata_Call {
	_c.Run(run)
	return _c
}

// SetKey provides a mock function with given fields: key
func (_m *MockServiceProvider) SetKey(key crypto.Signer) {
	_m.Called(key)
}

// MockServiceProvider_SetKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetKey'
type MockServiceProvider_SetKey_Call struct {
	*mock.Call
}

// SetKey is a helper method to define mock.On call
//   - key crypto.Signer
func (_e *MockServiceProvider_Expecter) SetKey(key interface{}) *MockServiceProvider_SetKey_Call {
	return &MockServiceProvider_SetKey_Call{Call: _e.mock.On("SetKey", key)}
}

func (_c *MockServiceProvider_SetKey_Call) Run(run func(key crypto.Signer)) *MockServiceProvider_SetKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(crypto.Signer))
	})
	return _c
}

func (_c *MockServiceProvider_SetKey_Call) Return() *MockServiceProvider_SetKey_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServiceProvider_SetKey_Call) RunAndReturn(run func(crypto.Signer)) *MockServiceProvider_SetKey_Call {
	_c.Run(run)
	return _c
}

// SetMetadataUrl provides a mock function with given fields: metadataUrl
func (_m *MockServiceProvider) SetMetadataUrl(metadataUrl url.URL) {
	_m.Called(metadataUrl)
}

// MockServiceProvider_SetMetadataUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMetadataUrl'
type MockServiceProvider_SetMetadataUrl_Call struct {
	*mock.Call
}

// SetMetadataUrl is a helper method to define mock.On call
//   - metadataUrl url.URL
func (_e *MockServiceProvider_Expecter) SetMetadataUrl(metadataUrl interface{}) *MockServiceProvider_SetMetadataUrl_Call {
	return &MockServiceProvider_SetMetadataUrl_Call{Call: _e.mock.On("SetMetadataUrl", metadataUrl)}
}

func (_c *MockServiceProvider_SetMetadataUrl_Call) Run(run func(metadataUrl url.URL)) *MockServiceProvider_SetMetadataUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(url.URL))
	})
	return _c
}

func (_c *MockServiceProvider_SetMetadataUrl_Call) Return() *MockServiceProvider_SetMetadataUrl_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServiceProvider_SetMetadataUrl_Call) RunAndReturn(run func(url.URL)) *MockServiceProvider_SetMetadataUrl_Call {
	_c.Run(run)
	return _c
}

// SetSloUrl provides a mock function with given fields: sloUrl
func (_m *MockServiceProvider) SetSloUrl(sloUrl url.URL) {
	_m.Called(sloUrl)
}

// MockServiceProvider_SetSloUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSloUrl'
type MockServiceProvider_SetSloUrl_Call struct {
	*mock.Call
}

// SetSloUrl is a helper method to define mock.On call
//   - sloUrl url.URL
func (_e *MockServiceProvider_Expecter) SetSloUrl(sloUrl interface{}) *MockServiceProvider_SetSloUrl_Call {
	return &MockServiceProvider_SetSloUrl_Call{Call: _e.mock.On("SetSloUrl", sloUrl)}
}

func (_c *MockServiceProvider_SetSloUrl_Call) Run(run func(sloUrl url.URL)) *MockServiceProvider_SetSloUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(url.URL))
	})
	return _c
}

func (_c *MockServiceProvider_SetSloUrl_Call) Return() *MockServiceProvider_SetSloUrl_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServiceProvider_SetSloUrl_Call) RunAndReturn(run func(url.URL)) *MockServiceProvider_SetSloUrl_Call {
	_c.Run(run)
	return _c
}

// SignArtifactResolve provides a mock function with given fields: req
func (_m *MockServiceProvider) SignArtifactResolve(req *saml.ArtifactResolve) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for SignArtifactResolve")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*saml.ArtifactResolve) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceProvider_SignArtifactResolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignArtifactResolve'
type MockServiceProvider_SignArtifactResolve_Call struct {
	*mock.Call
}

// SignArtifactResolve is a helper method to define mock.On call
//   - req *saml.ArtifactResolve
func (_e *MockServiceProvider_Expecter) SignArtifactResolve(req interface{}) *MockServiceProvider_SignArtifactResolve_Call {
	return &MockServiceProvider_SignArtifactResolve_Call{Call: _e.mock.On("SignArtifactResolve", req)}
}

func (_c *MockServiceProvider_SignArtifactResolve_Call) Run(run func(req *saml.ArtifactResolve)) *MockServiceProvider_SignArtifactResolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*saml.ArtifactResolve))
	})
	return _c
}

func (_c *MockServiceProvider_SignArtifactResolve_Call) Return(_a0 error) *MockServiceProvider_SignArtifactResolve_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_SignArtifactResolve_Call) RunAndReturn(run func(*saml.ArtifactResolve) error) *MockServiceProvider_SignArtifactResolve_Call {
	_c.Call.Return(run)
	return _c
}

// SignAuthnRequest provides a mock function with given fields: req
func (_m *MockServiceProvider) SignAuthnRequest(req *saml.AuthnRequest) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for SignAuthnRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*saml.AuthnRequest) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceProvider_SignAuthnRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignAuthnRequest'
type MockServiceProvider_SignAuthnRequest_Call struct {
	*mock.Call
}

// SignAuthnRequest is a helper method to define mock.On call
//   - req *saml.AuthnRequest
func (_e *MockServiceProvider_Expecter) SignAuthnRequest(req interface{}) *MockServiceProvider_SignAuthnRequest_Call {
	return &MockServiceProvider_SignAuthnRequest_Call{Call: _e.mock.On("SignAuthnRequest", req)}
}

func (_c *MockServiceProvider_SignAuthnRequest_Call) Run(run func(req *saml.AuthnRequest)) *MockServiceProvider_SignAuthnRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*saml.AuthnRequest))
	})
	return _c
}

func (_c *MockServiceProvider_SignAuthnRequest_Call) Return(_a0 error) *MockServiceProvider_SignAuthnRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_SignAuthnRequest_Call) RunAndReturn(run func(*saml.AuthnRequest) error) *MockServiceProvider_SignAuthnRequest_Call {
	_c.Call.Return(run)
	return _c
}

// SignLogoutRequest provides a mock function with given fields: req
func (_m *MockServiceProvider) SignLogoutRequest(req *saml.LogoutRequest) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for SignLogoutRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*saml.LogoutRequest) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceProvider_SignLogoutRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignLogoutRequest'
type MockServiceProvider_SignLogoutRequest_Call struct {
	*mock.Call
}

// SignLogoutRequest is a helper method to define mock.On call
//   - req *saml.LogoutRequest
func (_e *MockServiceProvider_Expecter) SignLogoutRequest(req interface{}) *MockServiceProvider_SignLogoutRequest_Call {
	return &MockServiceProvider_SignLogoutRequest_Call{Call: _e.mock.On("SignLogoutRequest", req)}
}

func (_c *MockServiceProvider_SignLogoutRequest_Call) Run(run func(req *saml.LogoutRequest)) *MockServiceProvider_SignLogoutRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*saml.LogoutRequest))
	})
	return _c
}

func (_c *MockServiceProvider_SignLogoutRequest_Call) Return(_a0 error) *MockServiceProvider_SignLogoutRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_SignLogoutRequest_Call) RunAndReturn(run func(*saml.LogoutRequest) error) *MockServiceProvider_SignLogoutRequest_Call {
	_c.Call.Return(run)
	return _c
}

// SignLogoutResponse provides a mock function with given fields: resp
func (_m *MockServiceProvider) SignLogoutResponse(resp *saml.LogoutResponse) error {
	ret := _m.Called(resp)

	if len(ret) == 0 {
		panic("no return value specified for SignLogoutResponse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*saml.LogoutResponse) error); ok {
		r0 = rf(resp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceProvider_SignLogoutResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignLogoutResponse'
type MockServiceProvider_SignLogoutResponse_Call struct {
	*mock.Call
}

// SignLogoutResponse is a helper method to define mock.On call
//   - resp *saml.LogoutResponse
func (_e *MockServiceProvider_Expecter) SignLogoutResponse(resp interface{}) *MockServiceProvider_SignLogoutResponse_Call {
	return &MockServiceProvider_SignLogoutResponse_Call{Call: _e.mock.On("SignLogoutResponse", resp)}
}

func (_c *MockServiceProvider_SignLogoutResponse_Call) Run(run func(resp *saml.LogoutResponse)) *MockServiceProvider_SignLogoutResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*saml.LogoutResponse))
	})
	return _c
}

func (_c *MockServiceProvider_SignLogoutResponse_Call) Return(_a0 error) *MockServiceProvider_SignLogoutResponse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_SignLogoutResponse_Call) RunAndReturn(run func(*saml.LogoutResponse) error) *MockServiceProvider_SignLogoutResponse_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAssertion provides a mock function with given fields: assertion, possibleRequestIDs, now
func (_m *MockServiceProvider) ValidateAssertion(assertion *saml.Assertion, possibleRequestIDs []string, now time.Time) error {
	ret := _m.Called(assertion, possibleRequestIDs, now)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAssertion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*saml.Assertion, []string, time.Time) error); ok {
		r0 = rf(assertion, possibleRequestIDs, now)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceProvider_ValidateAssertion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAssertion'
type MockServiceProvider_ValidateAssertion_Call struct {
	*mock.Call
}

// ValidateAssertion is a helper method to define mock.On call
//   - assertion *saml.Assertion
//   - possibleRequestIDs []string
//   - now time.Time
func (_e *MockServiceProvider_Expecter) ValidateAssertion(assertion interface{}, possibleRequestIDs interface{}, now interface{}) *MockServiceProvider_ValidateAssertion_Call {
	return &MockServiceProvider_ValidateAssertion_Call{Call: _e.mock.On("ValidateAssertion", assertion, possibleRequestIDs, now)}
}

func (_c *MockServiceProvider_ValidateAssertion_Call) Run(run func(assertion *saml.Assertion, possibleRequestIDs []string, now time.Time)) *MockServiceProvider_ValidateAssertion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*saml.Assertion), args[1].([]string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockServiceProvider_ValidateAssertion_Call) Return(_a0 error) *MockServiceProvider_ValidateAssertion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_ValidateAssertion_Call) RunAndReturn(run func(*saml.Assertion, []string, time.Time) error) *MockServiceProvider_ValidateAssertion_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateLogoutResponseForm provides a mock function with given fields: postFormData
func (_m *MockServiceProvider) ValidateLogoutResponseForm(postFormData string) error {
	ret := _m.Called(postFormData)

	if len(ret) == 0 {
		panic("no return value specified for ValidateLogoutResponseForm")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(postFormData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceProvider_ValidateLogoutResponseForm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateLogoutResponseForm'
type MockServiceProvider_ValidateLogoutResponseForm_Call struct {
	*mock.Call
}

// ValidateLogoutResponseForm is a helper method to define mock.On call
//   - postFormData string
func (_e *MockServiceProvider_Expecter) ValidateLogoutResponseForm(postFormData interface{}) *MockServiceProvider_ValidateLogoutResponseForm_Call {
	return &MockServiceProvider_ValidateLogoutResponseForm_Call{Call: _e.mock.On("ValidateLogoutResponseForm", postFormData)}
}

func (_c *MockServiceProvider_ValidateLogoutResponseForm_Call) Run(run func(postFormData string)) *MockServiceProvider_ValidateLogoutResponseForm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockServiceProvider_ValidateLogoutResponseForm_Call) Return(_a0 error) *MockServiceProvider_ValidateLogoutResponseForm_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_ValidateLogoutResponseForm_Call) RunAndReturn(run func(string) error) *MockServiceProvider_ValidateLogoutResponseForm_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateLogoutResponseRedirect provides a mock function with given fields: queryParameterData
func (_m *MockServiceProvider) ValidateLogoutResponseRedirect(queryParameterData string) error {
	ret := _m.Called(queryParameterData)

	if len(ret) == 0 {
		panic("no return value specified for ValidateLogoutResponseRedirect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(queryParameterData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceProvider_ValidateLogoutResponseRedirect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateLogoutResponseRedirect'
type MockServiceProvider_ValidateLogoutResponseRedirect_Call struct {
	*mock.Call
}

// ValidateLogoutResponseRedirect is a helper method to define mock.On call
//   - queryParameterData string
func (_e *MockServiceProvider_Expecter) ValidateLogoutResponseRedirect(queryParameterData interface{}) *MockServiceProvider_ValidateLogoutResponseRedirect_Call {
	return &MockServiceProvider_ValidateLogoutResponseRedirect_Call{Call: _e.mock.On("ValidateLogoutResponseRedirect", queryParameterData)}
}

func (_c *MockServiceProvider_ValidateLogoutResponseRedirect_Call) Run(run func(queryParameterData string)) *MockServiceProvider_ValidateLogoutResponseRedirect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockServiceProvider_ValidateLogoutResponseRedirect_Call) Return(_a0 error) *MockServiceProvider_ValidateLogoutResponseRedirect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_ValidateLogoutResponseRedirect_Call) RunAndReturn(run func(string) error) *MockServiceProvider_ValidateLogoutResponseRedirect_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateLogoutResponseRequest provides a mock function with given fields: req
func (_m *MockServiceProvider) ValidateLogoutResponseRequest(req *http.Request) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for ValidateLogoutResponseRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*http.Request) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceProvider_ValidateLogoutResponseRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateLogoutResponseRequest'
type MockServiceProvider_ValidateLogoutResponseRequest_Call struct {
	*mock.Call
}

// ValidateLogoutResponseRequest is a helper method to define mock.On call
//   - req *http.Request
func (_e *MockServiceProvider_Expecter) ValidateLogoutResponseRequest(req interface{}) *MockServiceProvider_ValidateLogoutResponseRequest_Call {
	return &MockServiceProvider_ValidateLogoutResponseRequest_Call{Call: _e.mock.On("ValidateLogoutResponseRequest", req)}
}

func (_c *MockServiceProvider_ValidateLogoutResponseRequest_Call) Run(run func(req *http.Request)) *MockServiceProvider_ValidateLogoutResponseRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *MockServiceProvider_ValidateLogoutResponseRequest_Call) Return(_a0 error) *MockServiceProvider_ValidateLogoutResponseRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_ValidateLogoutResponseRequest_Call) RunAndReturn(run func(*http.Request) error) *MockServiceProvider_ValidateLogoutResponseRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceProvider creates a new instance of MockServiceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceProvider {
	mock := &MockServiceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
