// Code generated by mockery. DO NOT EDIT.

package saml

import (
	etree "github.com/beevik/etree"
	dsig "github.com/russellhaering/goxmldsig"

	mock "github.com/stretchr/testify/mock"
)

// MockSignatureVerifier is an autogenerated mock type for the SignatureVerifier type
type MockSignatureVerifier struct {
	mock.Mock
}

type MockSignatureVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSignatureVerifier) EXPECT() *MockSignatureVerifier_Expecter {
	return &MockSignatureVerifier_Expecter{mock: &_m.Mock}
}

// VerifySignature provides a mock function with given fields: validationContext, el
func (_m *MockSignatureVerifier) VerifySignature(validationContext *dsig.ValidationContext, el *etree.Element) error {
	ret := _m.Called(validationContext, el)

	if len(ret) == 0 {
		panic("no return value specified for VerifySignature")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*dsig.ValidationContext, *etree.Element) error); ok {
		r0 = rf(validationContext, el)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSignatureVerifier_VerifySignature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifySignature'
type MockSignatureVerifier_VerifySignature_Call struct {
	*mock.Call
}

// VerifySignature is a helper method to define mock.On call
//   - validationContext *dsig.ValidationContext
//   - el *etree.Element
func (_e *MockSignatureVerifier_Expecter) VerifySignature(validationContext interface{}, el interface{}) *MockSignatureVerifier_VerifySignature_Call {
	return &MockSignatureVerifier_VerifySignature_Call{Call: _e.mock.On("VerifySignature", validationContext, el)}
}

func (_c *MockSignatureVerifier_VerifySignature_Call) Run(run func(validationContext *dsig.ValidationContext, el *etree.Element)) *MockSignatureVerifier_VerifySignature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dsig.ValidationContext), args[1].(*etree.Element))
	})
	return _c
}

func (_c *MockSignatureVerifier_VerifySignature_Call) Return(_a0 error) *MockSignatureVerifier_VerifySignature_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSignatureVerifier_VerifySignature_Call) RunAndReturn(run func(*dsig.ValidationContext, *etree.Element) error) *MockSignatureVerifier_VerifySignature_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSignatureVerifier creates a new instance of MockSignatureVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSignatureVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSignatureVerifier {
	mock := &MockSignatureVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
