// Code generated by mockery. DO NOT EDIT.

package saml

import (
	http "net/http"

	saml "github.com/adalundhe/saml-gin"
	mock "github.com/stretchr/testify/mock"
)

// MockServiceProviderProvider is an autogenerated mock type for the ServiceProviderProvider type
type MockServiceProviderProvider struct {
	mock.Mock
}

type MockServiceProviderProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceProviderProvider) EXPECT() *MockServiceProviderProvider_Expecter {
	return &MockServiceProviderProvider_Expecter{mock: &_m.Mock}
}

// GetServiceProvider provides a mock function with given fields: r, serviceProviderID
func (_m *MockServiceProviderProvider) GetServiceProvider(r *http.Request, serviceProviderID string) (*saml.EntityDescriptor, error) {
	ret := _m.Called(r, serviceProviderID)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceProvider")
	}

	var r0 *saml.EntityDescriptor
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request, string) (*saml.EntityDescriptor, error)); ok {
		return rf(r, serviceProviderID)
	}
	if rf, ok := ret.Get(0).(func(*http.Request, string) *saml.EntityDescriptor); ok {
		r0 = rf(r, serviceProviderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*saml.EntityDescriptor)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request, string) error); ok {
		r1 = rf(r, serviceProviderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceProviderProvider_GetServiceProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceProvider'
type MockServiceProviderProvider_GetServiceProvider_Call struct {
	*mock.Call
}

// GetServiceProvider is a helper method to define mock.On call
//   - r *http.Request
//   - serviceProviderID string
func (_e *MockServiceProviderProvider_Expecter) GetServiceProvider(r interface{}, serviceProviderID interface{}) *MockServiceProviderProvider_GetServiceProvider_Call {
	return &MockServiceProviderProvider_GetServiceProvider_Call{Call: _e.mock.On("GetServiceProvider", r, serviceProviderID)}
}

func (_c *MockServiceProviderProvider_GetServiceProvider_Call) Run(run func(r *http.Request, serviceProviderID string)) *MockServiceProviderProvider_GetServiceProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request), args[1].(string))
	})
	return _c
}

func (_c *MockServiceProviderProvider_GetServiceProvider_Call) Return(_a0 *saml.EntityDescriptor, _a1 error) *MockServiceProviderProvider_GetServiceProvider_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceProviderProvider_GetServiceProvider_Call) RunAndReturn(run func(*http.Request, string) (*saml.EntityDescriptor, error)) *MockServiceProviderProvider_GetServiceProvider_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceProviderProvider creates a new instance of MockServiceProviderProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceProviderProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceProviderProvider {
	mock := &MockServiceProviderProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
